src/app/(dashboard)/(home)/pending/forms/pending-inputs.tsx
src/app/(dashboard)/(home)/pending/forms/pending-schema.ts
src/app/(dashboard)/(home)/pending/update-pending-form.tsx

Renamed "Mode of Premium" to "Mode of Payment" throughout the pending form components.
- Updated variable names and form field references from `mode_of_premium` to `mode_of_payment`
- Changed the placeholder text in the select input from "Select HMO Provider" to "Select Mode of Payment"
- Updated the schema to use `mode_of_payment_id` instead of `mode_of_premium_id`
- Modified the validation check and error message in the form submission handler
1. Navigate to the pending form in the dashboard
2. Verify that the dropdown label now reads "Mode of Payment"
3. Check that the placeholder text in the dropdown is "Select Mode of Payment"
4. Submit the form without selecting a mode of payment and confirm the error message reads "Mode of payment is required"
This change improves clarity and …

TIM-396 REFACTOR(pending): mode of premium to mode of payment in forms

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-about.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-delete-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-edit-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-page.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/page.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/delete-company-schema.ts

Added a company delete functionality and improved the layout of company edit and delete buttons.
- Introduced a new `CompanyDeleteButton` component for deleting company accounts
- Added a delete company schema for form validation
- Updated the `CompanyPage` component to include the delete button for users with the 'marketing' role
- Improved the layout and styling of edit and delete buttons
- Refactored imports and removed unused code in `company-about.tsx`
- Updated the `CompanyEditButton` styling for better responsiveness
1. Log in as a user with the 'marketing' role
2. Navigate to a company's page
3. Verify that both edit and delete buttons are visible
4. Click the delete button and attempt to delete the company
5. Confirm that the deletion process requires entering the company name
6. …

feat(accounts): add delete account function

---

src/app/(dashboard)/(home)/accounts/columns/accounts-columns.tsx
src/app/(dashboard)/(home)/billing-statements/data-table-row.tsx
src/app/(dashboard)/(home)/billing-statements/data-table.tsx
src/app/(dashboard)/(home)/billing-statements/forms/disabled-inputs.tsx
src/app/(dashboard)/(home)/billing-statements/forms/pending-inputs.tsx
src/app/(dashboard)/(home)/billing-statements/forms/pending-schema.ts
src/app/(dashboard)/(home)/billing-statements/page.tsx
src/app/(dashboard)/(home)/billing-statements/pending-columns.tsx
src/app/(dashboard)/(home)/billing-statements/pending-table.tsx
src/app/(dashboard)/(home)/billing-statements/update-pending-form.tsx
src/components/layout/navigation.tsx

Added billing statements functionality with pending accounts management.
- Created new components for billing statements, including a data table, columns definition, and update form.
- Implemented pending accounts management with disabled and editable inputs.
- Added a new navigation item for billing statements.
- Created schemas and form validation for pending accounts.
- Integrated with Supabase for data fetching and mutations.
1. Log in as a user with the 'finance' role.
2. Navigate to the new "Billing Statements" page.
3. Verify that the pending accounts table loads correctly.
4. Try updating a pending account by clicking on a row and filling out the form.
5. Confirm that the update is successful and reflected in the table.
This change introduces a new feature for managing billing …

TIM-435 feat(billing-statements): add billing statements page

---

src/app/(dashboard)/(home)/billing-statements/data-table.tsx

Enhanced the Billing Statements data table with dynamic count and improved UI elements.
- Added a dynamic count of billing statements using Supabase query
- Replaced static "CHANGE ME" description with actual statement count
- Implemented loading state with Skeleton component for count display
- Removed unused imports and commented-out code
- Integrated Supabase client and React Query for data fetching
1. Navigate to the Billing Statements page
2. Verify that the page displays the correct number of billing statements
3. Check if a loading skeleton appears briefly before the count is displayed
4. Ensure the data table and search functionality work as expected
This change provides users with accurate, real-time information about the number of billing statements. It also improves the user …

TIM-439 feat(billing-statements): add total count on header

---

src/app/(dashboard)/(home)/billing-statements/billing-statement-schema.ts
src/components/billing-statement/billing-statement-modal.tsx

Enhanced input validation and data handling in billing statement functionality.
- Updated `BillingStatementSchema` to handle empty string and undefined values for numeric fields.
- Made `account_id` a required field in the schema.
- Improved data reset logic in `BillingStatementModal` component to handle null values.
1. Open the billing statement form.
2. Try submitting the form with empty fields and verify that validation works correctly.
3. Edit an existing billing statement and ensure that all fields, including those with null values, are properly populated.
4. Attempt to create or edit a billing statement without an `account_id` and confirm that it's not allowed.
These changes improve data integrity and user experience by:
1. Preventing unintended conversions of empty strings to zero …

TIM-449 fix(billing-statements): allow undefined values to be submitted to form

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/billing-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/billing-statements.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-page.tsx
src/queries/get-billing-statement-inputs.ts

will change mode of payment tomorrow mwa
Enhanced billing information display and functionality for personnel accounts.
- Updated `BillingInformation` component to dynamically display data from the `billing_statements` table.
- Modified `BillingStatements` component to fetch and display multiple billing statements for a company.
- Added date formatting for better readability.
- Updated `CompanyPage` to pass `companyId` to `BillingStatements`.
- Adjusted `getBillingStatementInputs` query to include `created_at` and rename `mode_of_premium_id` to `mode_of_payment_id`.
1. Navigate to a personnel account page.
2. Check the "Billing Statements" tab.
3. Verify that multiple billing statements are displayed with correct dates.
4. Expand a billing statement and confirm that all fields are …

TIM-457 Fetch billing statement inputs

---

supabase/migrations/20241020235146_update_company_employees_rls.sql

Updated row-level security policies for company employees table to allow access for multiple departments.
- Dropped existing policies for updating and inserting company employees.
- Created new policies allowing all departments except 'agent' to update and insert company employees.
- Departments with access now include marketing, after-sales, under-writing, finance, and admin.
1. Log in as users from different departments (marketing, after-sales, under-writing, finance, admin, and agent).
2. Attempt to update and insert records in the company_employees table.
3. Verify that users from all departments except 'agent' can perform these operations.
4. Confirm that users from the 'agent' department cannot update or insert records.
This change expands access to the company_employees table …

TIM-459 REFACTOR(employees): allow all roles to insert/edit company-employees

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-form-modal.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-form.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-columns.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-data-table.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-provider.tsx

Refactored employee management functionality to support both adding and editing employees.
- Renamed `AddEmployeeModal` to `EmployeeFormModal` and updated it to handle both adding and editing employees.
- Enhanced `EmployeeForm` to pre-populate fields when editing an existing employee.
- Updated `employeesColumns` to include an edit action in the dropdown menu.
- Modified `EmployeesDataTable` to use the new `EmployeeFormModal` component.
- Updated `CompanyProvider` to include state for managing the currently edited employee data.
1. Navigate to the employees page for a company.
2. Try adding a new employee using the "Add Employee" button.
3. Verify that the new employee appears in the table.
4. Click the dropdown menu for an existing employee and select "Edit".
5. Confirm that the edit …

TIM-462 feat(employees): add edit employees function

---

package.json
pnpm-lock.yaml
src/app/(dashboard)/(home)/accounts/data-table.tsx
src/app/(dashboard)/(home)/accounts/export-accounts.tsx

Added an export functionality for accounts data to Excel format.
- Added `xlsx` package to dependencies
- Created a new `ExportAccounts` component
- Integrated the export functionality into the accounts data table
- Implemented logic to format and export account data to an Excel file
2. Look for the new "Export" button with a file download icon
3. Click the button to generate and download an Excel file
4. Open the downloaded file and verify that it contains the correct account data with formatted fields
This change provides users with the ability to easily export account data for offline analysis, reporting, or backup purposes. The Excel format allows for better data manipulation and integration with other tools, enhancing the overall utility of the …

feat(accounts): add export functionality to Excel

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-data-table.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-employees.tsx
src/queries/get-employee-by-company-id.ts

Added an export functionality for employees data in the Personnel module.
- Introduced a new `ExportEmployees` component that allows exporting employee data to an Excel file.
- Updated the `EmployeesDataTable` component to include the new export button alongside the "Add Employee" button.
- Modified the `getEmployeeByCompanyId` query to select only the necessary fields for export.
1. Navigate to the Personnel module for a specific company.
2. Locate the new "Export" button next to the "Add Employee" button.
3. Click the "Export" button.
4. Verify that an Excel file is downloaded with the current date in the filename.
5. Open the Excel file and confirm that it contains the correct employee data without sensitive fields like `id` and `account_id`.
This change provides users with a …

feat(employees): add export functionality and refine data table

---

src/app/(dashboard)/(home)/billing-statements/page.tsx
src/app/(dashboard)/admin/layout.tsx
src/components/layout/navigation.tsx
src/utils/page-protect.ts
supabase/migrations/20241023134424_admin_to_billing_statments_rls.sql

Extended billing statement access and management to admin users.
- Modified `pageProtect` function to accept an array of departments instead of a single department.
- Updated `BillingStatementsPage` and `AdminLayout` to use the new `pageProtect` function signature.
- Adjusted the Navigation component to show the Billing Statements tab for both finance and admin roles.
- Added new SQL migration to update row-level security policies for the `billing_statements` table, allowing admin users to read, insert, and update billing statements alongside finance users.
1. Log in as an admin user.
2. Verify that the Billing Statements tab is visible in the navigation.
3. Access the Billing Statements page and ensure it loads without redirecting.
4. Attempt to read, insert, and update billing …

feat(billing): grant admin access to billing statements and RLS

---

src/app/(dashboard)/(home)/accounts/page.tsx

Added page protection to the Accounts page.
- Imported the `pageProtect` function from `@/utils/page-protect`.
- Implemented `pageProtect` with an array of allowed roles: 'marketing', 'after-sales', 'under-writing', 'finance', and 'admin'.
1. Log in with different user roles.
2. Attempt to access the Accounts page.
3. Verify that only users with the specified roles can view the page.
4. Ensure users without the allowed roles are redirected or shown an appropriate error message.
To enhance security and access control for the Accounts page, ensuring that only authorized personnel with specific roles can view sensitive account information.

TIM-456 feat(accounts): add role check on accounts page

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-about.tsx

Removed form reset after company about section update
Removed the `form.reset()` call and an unused commented-out query invalidation in the success handler of the company about section
1. Navigate to a company's about section
2. Edit and save the form
3. Verify that the form remains populated with the updated values after saving
Resetting the form after a successful update was clearing the displayed values, creating a confusing user experience where the updated information would momentarily disappear before being re-fetched and displayed

fix(accounts): remove form reset after company update

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-about.tsx

Improved handling of optional account properties and date conversions in the company profile form.
Added null checks before accessing nested properties and date conversions in the company profile form initialization. Each property now safely handles undefined values by using optional chaining and providing empty fallback values.
1. Navigate to a company profile page
2. Verify form loads correctly with both complete and incomplete account data
3. Check that dates are properly displayed when present
4. Confirm that the form handles missing or null values without errors
To prevent runtime errors when accessing nested properties of potentially undefined account data and improve the robustness of date handling in the form initialization process.

fix(accounts): handle null values in company profile form

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-HMO-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-account-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-contract-information.tsx

Added null checks for company profile information fields to prevent rendering errors
Added conditional checks before accessing nested object properties in company profile components. This includes checks for:
- HMO Provider details
- Account Type information
- Mode of Payment data
- Plan Type information
- Previous and Current HMO Provider details
1. Navigate to a company profile page
2. Verify that fields display empty strings when their corresponding data is null
3. Confirm that fields still display correctly when data is present
4. Test with accounts that have missing or incomplete information
Prevents potential runtime errors when accessing properties of undefined objects, improving the application's stability and error handling. This is particularly important when dealing with …

fix(accounts): handle null HMO and account type values

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-schema.ts
src/types/database.types.ts
supabase/migrations/20241024083102_change_maximum_benefit_limit_data_type.sql

Changed the `maximum_benefit_limit` field from number to string type in the company employees table.
- Modified the `maximum_benefit_limit` column in `company_employees` table to use `varchar(255)` instead of a numeric type
- Updated the employee schema to handle `maximum_benefit_limit` as a string
- Updated database types to reflect the new string type for `maximum_benefit_limit`
- Removed unused database relationships
1. Run the migration to update the database schema
2. Verify that employee forms accept string values for maximum benefit limit
3. Confirm existing employee records display correctly with the new data type
4. Test creating and updating employees with various benefit limit values
To accommodate benefit limits that may include special characters, currency symbols, or …

fix(employees): change maximum benefit limit to string type

---

src/components/billing-statement/billing-statement-modal.tsx

Improved form data handling in the billing statement modal by implementing safer type checking and null handling.
- Replaced direct object assignment with conditional checks for account and mode of payment IDs
- Added explicit type checking for nested objects
- Implemented separate date handling for `due_date` and `or_date`
- Removed `@ts-ignore` comments by properly handling types
1. Open a billing statement with existing data
2. Verify that form fields are populated correctly
3. Check that dates, account IDs, and payment modes are displayed properly
4. Ensure no console errors appear related to type checking
The previous implementation relied on type ignores and unsafe assumptions about object structure. This change makes the code more robust by adding proper type checking and null …

fix(billing): improve form reset handling in billing statement modal

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-HMO-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-contract-information.tsx

Updated Input components to handle number values correctly in company profile forms.
- Modified the `Input` components in `company-HMO-information.tsx` and `company-contract-information.tsx` files.
- Added `value={field.value?.toString()}` to ensure proper rendering of number values in the input fields.
1. Navigate to the company profile pages containing HMO information and contract information.
2. Enter numeric values in the "Total Premium Paid", "Initial Contract Value", and "Initial Head Count" fields.
3. Verify that the entered values are displayed correctly and can be edited without issues.
This change addresses a potential issue where number values might not be properly handled or displayed in the input fields. By explicitly converting the value to a string, we ensure consistent …

TIM-493 fix(company): edit input build errors

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(billing statements)/billing-statements.tsx
src/components/billing-statement/billing-statement-modal.tsx
src/components/billing-statement/delete-billing-statement.tsx
src/queries/get-billing-statement-by-company-id.ts

Added delete functionality for billing statements and improved the UI layout.
- Added a delete button for billing statements in the billing statements list view
- Improved the layout of billing information and delete button in the collapsible content
- Updated the delete billing statement component to optionally close the modal after deletion
- Modified the billing statement query to only fetch active statements
- Added error handling and success messages for the delete operation
1. Navigate to the billing statements page for a company
2. Expand a billing statement and verify the delete button is present
3. Click the delete button and confirm the deletion
4. Check that the billing statement is removed from the list
5. Open a billing statement in the modal and test the delete functionality …

TIM-494 feat(billing-statements): add Delete Billing Statements button on company profile page

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-account-information.tsx
src/app/(dashboard)/(home)/accounts/accounts-schema.ts
src/app/(dashboard)/(home)/accounts/forms/marketing-inputs.tsx
src/components/maskito/percentage-options.ts

Implemented percentage masking for commission rate inputs and updated validation.
- Added `useMaskito` hook with percentage options for commission rate inputs in both company account information and marketing inputs forms.
- Updated the `commision_rate` field in the accounts schema to enforce a range between 0 and 100.
- Replaced the number input for commission rate with a masked text input.
- Removed unused `dateOptions` from the maskito options file.
- Created a new `percentage-options.ts` file with custom maskito options for percentage inputs.
1. Navigate to the company account information or marketing inputs form.
2. Attempt to enter commission rates:
- Try entering values between 0% and 100%
- Attempt to enter values outside this range
- Check that decimal places are limited to two
- …

feat(commission): implement percentage input mask for commission rate

---

src/app/(dashboard)/(home)/accounts/accounts-schema.ts
src/app/(dashboard)/(home)/accounts/forms/marketing-inputs.tsx
src/components/maskito/currency-options.ts

Enhanced form validation and input formatting for the accounts schema and marketing inputs.
- Updated `accountsSchema` with more specific validations:
- Added max length constraints for string fields
- Specified UUID format for ID fields
- Improved parsing for numeric fields, including currency handling
- Added email validation for contact person's email address
- Modified `MarketingInputs` component:
- Implemented currency masking for total premium paid and initial contract value
- Refined commission rate input with percentage masking
- Adjusted input types and event handlers for better user experience
- Added a new `currency-options.ts` file with currency formatting options
1. Navigate to the accounts form in the dashboard
2. Test input fields with various valid and invalid inputs:
- …

TIM-511 feat(accounts): add input masking for currencies on "create new account"

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-HMO-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-contract-information.tsx

Added currency masking to input fields for total premium paid and initial contract value.
- Implemented `useMaskito` hook with currency options for the "Total Premium Paid" input in the company HMO information section.
- Added similar currency masking for the "Initial Contract Value" input in the company contract information section.
- Replaced `type="number"` with custom masked inputs for better currency formatting.
- Updated input handling to use `onInput` instead of direct value assignment.
1. Navigate to the company profile page.
2. Enter values in the "Total Premium Paid" field in the HMO information section.
3. Enter values in the "Initial Contract Value" field in the contract information section.
4. Verify that the inputs are formatted as currency (e.g., with commas for thousands …

TIM-512 feat(accounts): add currency masking on "edit account form"

---

src/app/(dashboard)/(home)/billing-statements/billing-statement-schema.ts
src/components/billing-statement/billing-statement-modal.tsx
src/components/maskito/percentage-options.ts

Enhanced billing statement form with currency and percentage input masking.
- Updated `BillingStatementSchema` to handle currency formatting and parsing
- Implemented Maskito for currency and percentage input fields in the billing statement modal
- Added currency and percentage masking to form fields: amount, total contract value, balance, amount billed, amount paid, commission rate, and commission earned
- Improved data handling when editing existing billing statements
- Added table rerendering functionality to ensure updates are reflected immediately
1. Open the billing statement modal for creating or editing a statement
2. Enter values in the currency fields (e.g., amount, total contract value) and observe the automatic formatting
3. Enter a percentage in the commission rate field and …

TIM-513 feat(billing-statements): add masking on input form

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-about.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-contract-information.tsx

Added currency and percentage masking to company profile fields and removed unused code.
- Implemented currency masking for `total_premium_paid` and `initial_contract_value` fields
- Added percentage masking for `commision_rate` field
- Imported `currencyOptions` and `percentageOptions` from maskito components
- Removed unused `setEditMode` from `useCompanyEditContext()`
- Removed unused query for `modeOfPremiums` and its loading state
1. Navigate to a company's profile page
2. Verify that `total_premium_paid` and `initial_contract_value` fields display currency formatting
3. Check that the `commision_rate` field shows percentage formatting
4. Ensure that the company profile loads correctly without any errors related to removed code
This change improves data consistency and user …

feat(company): implement currency and percentage input masks

---

src/app/(dashboard)/(home)/accounts/forms/marketing-inputs.tsx
src/components/billing-statement/billing-statement-modal.tsx

Improved billing statement modal functionality and form handling.
- Replaced separate insert and update mutations with a single upsert mutation for billing statements.
- Updated form submission logic to use the new upsert mutation.
- Simplified state management by removing unnecessary query client invalidation.
- Improved toast messages to differentiate between creation and update actions.
- Added `disabled` prop to additional input fields in the marketing inputs form.
1. Open the billing statement modal.
2. Create a new billing statement and verify it's added successfully.
3. Edit an existing billing statement and confirm the changes are saved.
4. Check that appropriate toast messages appear for both creation and update actions.
5. Verify that form fields are disabled during submission. …

TIM-514 feat(billing-statements): improve upsert mutation when creating/editing billing statements

---

supabase/migrations/20241027110502_delete_rcp_search_function.sql

Removed unused search functions from the database.
This migration removes two SQL functions:
- `public.search_billing_statements`
- `public.search_accounts`
1. Apply the migration to your local database.
2. Attempt to call these functions in your SQL client or application.
3. Verify that you receive an error indicating that these functions no longer exist.
These search functions are no longer used in the application, and removing them helps to clean up the database schema. This change reduces clutter and potential confusion for developers working on the project.

TIM-517 delete(rpc): unused rpc search functions

---

supabase/migrations/20241027122803_fix_postgres_warning_on_rls_auth_uid.sql

Updated Row Level Security (RLS) policies to use `auth.uid()` instead of `auth.jwt()`.
This migration drops and recreates various Row Level Security (RLS) policies across multiple tables in the database. The key change is replacing `auth.jwt()` with `auth.uid()` in the policy definitions. This affects tables such as `account_types`, `accounts`, `accounts_column_visibility`, `activity_logs`, `billing_statements`, `company_employees`, `hmo_providers`, `mode_of_payments`, `mode_of_premium`, and `plan_types`.
1. Apply the migration to a test database.
2. Attempt to perform CRUD operations on the affected tables using different user roles (admin, finance, marketing, etc.).
3. Verify that the permissions are still correctly enforced according to the user's role and department.
4. Check that no …

fix(rls): update PostgreSQL RLS policies to use auth.uid()

---

src/app/(dashboard)/admin/agents/create/add-agent-form.tsx
src/app/(dashboard)/admin/agents/create/add-agent.tsx

Enhanced the Add Agent functionality with improved state management and query invalidation.
- Added `setIsOpen` prop to `AddAgentForm` component for better control of the form's visibility.
- Implemented `useQueryClient` hook to invalidate queries after form submission.
- Removed commented-out delete button from the form.
- Introduced `isOpen` state in the `AddAgent` component to control the Sheet's open/close state.
- Updated the Sheet component to use the `isOpen` state for better control.
1. Navigate to the Admin Agents page.
2. Click the "Add Agent" button to open the form.
3. Fill out the form and submit.
4. Verify that the form closes automatically upon successful submission.
5. Check that the agents list updates immediately without manual refresh.
This change improves the user …

feat(agents): improve add agent form with query invalidation and modal closure

---

src/app/(dashboard)/(home)/accounts/add-account-form.tsx

Added redirection to the newly created account page after successful form submission.
- Imported `useRouter` from Next.js navigation
- Added `data` to the destructured values from `useInsertMutation`
- Implemented a `useEffect` hook to redirect the user to the new account page after successful creation
- Removed a console.log statement for error handling
1. Navigate to the account creation form
2. Fill out the form with valid data
3. Submit the form
4. Verify that you are automatically redirected to the newly created account's page
This change improves the user experience by automatically redirecting users to the newly created account page after successful form submission. It eliminates the need for manual navigation and provides immediate access to the new account's details.

feat(accounts): redirect to new account after creation

---

src/app/(dashboard)/(home)/accounts/data-table.tsx

Refactored account data fetching and display in the DataTable component.
- Imported a new `getAccounts` query function from '@/queries/get-accounts'
- Replaced the inline Supabase query with the new `getAccounts` function
- Updated the variable names from `totalCount` to `count` for consistency
- Modified the PageDescription to use the new `count` variable
2. Verify that the total number of accounts is displayed correctly
3. Check that the loading state (Skeleton) works as expected
4. Ensure that adding or removing accounts updates the count accurately
This change improves code organization by moving the account fetching logic into a separate query function. It enhances maintainability and reusability of the data fetching process across the application. …

feat(accounts): refactor account count fetching with getAccounts query

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-delete-button.tsx

Enhanced the company delete functionality with improved UI feedback and error handling.
- Added a loading spinner to the delete button during the deletion process
- Disabled the input field and delete button when the deletion is in progress or successful
- Removed console logging of errors
- Updated the mutation to use `null` instead of `'id'` for the third parameter
- Added `isSuccess` state to manage UI after successful deletion
1. Navigate to a company profile page
2. Click on the delete button
3. Enter the company name in the confirmation dialog
4. Submit the deletion request
5. Verify that the input field and delete button are disabled during the process
6. Confirm that a loading spinner appears on the delete button
7. Check that you're redirected to the accounts page after …

feat(company): enhance delete account functionality and UI

---

src/app/(dashboard)/(home)/accounts/export-accounts.tsx

Enhanced data handling in account export functionality
- Updated the `accountsData` mapping to include null checks for all fields
- Added fallback to empty string ('') for fields that might be undefined
- Improved the formatting of the agent name by using template literals
1. Navigate to the accounts export feature
2. Attempt to export accounts with various data configurations, including:
- Accounts with missing or undefined fields
- Accounts with complete data
3. Verify that the exported data handles all scenarios without errors
4. Check that empty fields are represented as blank entries rather than 'undefined'
This change improves the robustness of the account export feature by handling potential undefined values. It prevents errors that could occur when accessing properties of null …

feat(accounts): add null checks for account export fields

---

src/components/billing-statement/billing-statement-modal.tsx
src/components/billing-statement/delete-billing-statement.tsx
src/components/confirmation-dialog/confirmationStore.ts

Improved billing statement deletion process and enhanced confirmation dialog functionality.
- Updated `BillingStatementModal` to pass `setOpen` function to `DeleteBillingStatement` component
- Modified `DeleteBillingStatement` to close the modal after successful deletion instead of reloading the page
- Added `confirmationButtonVariant` option to the confirmation dialog for destructive actions
1. Open a billing statement modal for an existing statement
2. Click the delete button
3. Confirm the deletion in the confirmation dialog
4. Verify that the modal closes and the statement is removed without page reload
This change improves the user experience by providing a smoother deletion process for billing statements. It eliminates the need for a full page reload, making the application more …

feat(billing): enhance delete billing statement functionality and UI

---

src/app/(dashboard)/(home)/accounts/columns/accounts-columns.tsx

Enhanced date formatting and added accessorFn for various columns in the accounts table.
- Imported the `format` function from `date-fns` library.
- Added `accessorFn` to the "Agent" column to properly format the agent's full name.
- Implemented `accessorFn` for date-related columns to format dates using the `MMMM dd, yyyy` pattern.
- Applied date formatting to the following columns:
- Effectivity Date
- COC Issue Date
- Expiration Date
- Delivery Date of Membership IDs
- Orientation Date
- Wellness Lecture Date
- Annual Physical Examination Date
1. Navigate to the accounts table in the dashboard.
2. Verify that the "Agent" column displays full names correctly.
3. Check that all date columns (listed above) are formatted as "Month DD, YYYY".
4. Ensure that empty date fields are displayed …

feat(accounts): format date fields and enhance agent name display

---

src/app/(dashboard)/(home)/accounts/add-account-button.tsx

Simplified the AddAccountButton component by removing role-based access control.
- Removed the `useQuery` hook for fetching user roles
- Eliminated the `allowedRole` array and associated role check
- Removed the import for `getRole` utility function
2. Verify that the "Add Account" button is visible for all users, regardless of their role
3. Ensure the button still opens the dialog when clicked
This change simplifies the component and removes role-based restrictions on the "Add Account" button. It suggests that the decision was made to allow all users to access this functionality, potentially streamlining the user experience and reducing complexity in the codebase.

feat(accounts): remove role-based access control from AddAccountButton

---

src/queries/get-all-accounts.ts
src/queries/get-billing-statements.ts

Filter active accounts in queries and join statements
- In `get-all-accounts.ts`, added a filter to only return active accounts
- In `get-billing-statements.ts`, updated the join with accounts table to use inner join and include `is_active` field
- Added a filter to ensure only active accounts are included in billing statements
1. Run the `getAllAccounts` query and verify that only active accounts are returned
2. Execute the `getBillingStatements` query and confirm that:
- Only billing statements associated with active accounts are retrieved
- The `account` object in the results includes the `is_active` field
To ensure that queries only return data for active accounts, improving data consistency and preventing potential issues with inactive accounts in the system. This change also allows …

TIM-550 fix(billing-statements): billing statements should also be deleted when its parent account is deleted

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-HMO-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-account-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-contract-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-information-item.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-information.tsx

Refactored company profile components and introduced a reusable CompanyInformationItem component.
- Created a new `CompanyInformationItem` component in a separate file.
- Updated imports and removed duplicate `CompanyInformationItem` definitions in various files.
- Standardized the display of empty values to show a dash ('-') instead of 'No data'.
- Adjusted the rendering of agent names and dates to use `undefined` for consistency.
- Removed unused imports and variables.
1. Navigate to the company profile pages for different accounts.
2. Verify that all information is displayed correctly, with empty values showing as '-'.
3. Check that dates and agent names are formatted properly.
4. Ensure that the edit mode functionality still works as expected.
This refactoring improves code …

feat(company): refactor CompanyInformationItem and improve data display

---

src/types/database.types.ts
supabase/migrations/20241031034911_add_pending_accounts_table.sql
supabase/migrations/20241031041800_add_rls_to_pending_accounts_table.sql

Added a new `pending_accounts` table with row-level security policies to manage account approval workflows.
- Created a new `pending_accounts` table with fields matching the existing accounts structure
- Added foreign key relationships to related tables (account_types, company_employees, etc.)
- Implemented row-level security policies:
- Admin users have full access
- Regular users can only insert, select, and update records they created
- Added timestamps and approval status tracking fields
- Granted necessary permissions to anon, authenticated, and service role users
1. Create a new pending account as a non-admin user
2. Verify you can only view and edit your own pending accounts
3. Login as admin and confirm full access to all pending accounts
4. Attempt to access pending accounts as …

feat(pending): add pending accounts table

---

src/app/(dashboard)/(home)/accounts/data-table.tsx
src/app/(dashboard)/(home)/accounts/request/account-request-list-item.tsx
src/app/(dashboard)/(home)/accounts/request/account-request-list.tsx
src/app/(dashboard)/(home)/accounts/request/account-request.tsx
src/app/(dashboard)/(home)/accounts/request/delete-request.tsx
src/components/table-view-options.tsx
src/components/ui/badge.tsx
src/queries/get-pending-accounts.ts
supabase/migrations/20241031094042_add_update_rls_on_pending_accounts_table.sql

Added a new account request management system to track and handle pending account submissions.
- Added a new "Requests" button in the accounts table header showing the count of pending requests
- Created a dialog component to display pending account submissions
- Implemented request list items with badges indicating operation type (Add/Edit/Delete)
- Added ability to cancel/delete pending requests
- Set up RLS policies for pending accounts table to manage access control
- Added new database queries to fetch pending account data
2. Click on the "Requests" button in the table header
3. Verify pending requests are displayed with appropriate badges
4. Test canceling a request:
- Click "Cancel" on a request
- Confirm deletion when prompted
- Verify request is …

TIM-568 feat(accounts): add submission request list

---

src/app/(dashboard)/admin/approval-request/approval-request-data-table-row.tsx
src/app/(dashboard)/admin/approval-request/approval-request-table.tsx
src/app/(dashboard)/admin/approval-request/approval-rerquest-columns.tsx
src/app/(dashboard)/admin/approval-request/page.tsx
src/components/layout/admin-navigation.tsx
src/components/table-search.tsx
src/queries/get-pending-accounts.ts

Added a new approval request management interface for administrators to review and process pending account requests.
- Created a new approval request table view with sorting and filtering capabilities
- Added approval request columns showing action type, account name, and request timestamp
- Implemented approve/reject action buttons for each request
- Added a new "Approval Requests" navigation item in the admin sidebar
- Enhanced the table search component to accept custom placeholder text
- Updated the pending accounts query to support customizable sort order
1. Log in as an administrator
2. Navigate to the new "Approval Requests" section in the admin sidebar
3. Verify the table displays pending account requests with correct information
4. Test search functionality using the search bar …

feat(admin): add approval request table and management interface

---

src/app/(dashboard)/(home)/accounts/add-account-form.tsx
src/types/database.types.ts
supabase/migrations/20241102150409_change_company_name_to_be_unique.sql

Added validation to prevent duplicate company names when creating new accounts.
Added checks against both `pending_accounts` and `accounts` tables to verify if a company name already exists before allowing account creation. If a duplicate is found, an error message is displayed to the user.
1. Attempt to create a new account with a company name that already exists in the `pending_accounts` table
2. Verify that an error message "Account already exists" appears
3. Attempt to create a new account with a company name that already exists in the `accounts` table
4. Verify that an error message "Account already exists" appears
5. Create an account with a unique company name and verify it succeeds
To prevent duplicate company entries in the system and maintain data integrity across both pending …

feat(accounts): add company name uniqueness validation

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-about.tsx
src/app/(dashboard)/admin/approval-request/accounts/accounts-approval-columns.tsx
src/app/(dashboard)/admin/approval-request/accounts/action-request-button.tsx

Implemented approval workflow for company profile updates with pending changes system
- Modified company profile updates to create pending changes instead of direct updates
- Added operation type badges to display pending action types
- Changed account updates to use upsert instead of direct updates
- Implemented user tracking for pending changes
- Enhanced approval request handling with proper account ID mapping
1. Edit a company profile and submit changes
2. Verify changes appear in the approval request queue
3. Test both approve and reject actions on pending changes
4. Confirm approved changes are reflected in the main account
5. Verify operation type badges display correctly
6. Check that user tracking is working for pending changes
To implement a proper approval workflow for company …

feat(accounts): implement pending accounts approval workflow

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-edit-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/edit-pending-request.tsx

Added a pending request check before allowing company profile edits
- Enhanced the CompanyEditButton to check for existing pending requests
- Created a new EditPendingRequest dialog component
- Added functionality to delete pending requests
- Implemented user notifications for request actions
1. Log in as a user with appropriate role permissions
2. Navigate to a company profile
3. Click the "Edit Company Details" button
4. If there's a pending request:
- Verify the pending request dialog appears
- Test deleting the request
- Confirm toast notifications work
5. If no pending request:
- Verify edit mode activates normally
To prevent multiple concurrent edit requests and maintain better control over company profile changes by ensuring only one pending request exists at a time. This improves …

feat(company): add pending edit request handling for company details

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-about.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-delete-button.tsx
src/app/(dashboard)/admin/approval-request/accounts/action-request-button.tsx
src/queries/get-pending-accounts.ts
src/types/database.types.ts
supabase/migrations/20241103003332_add_is_delete_account_column_to_pending_accounts.sql

Added approval workflow for company deletion and improved user feedback for edit requests.
- Company deletion now requires admin approval instead of immediate deletion
- Added success toast notifications for edit request submissions
- Implemented check for existing pending requests before submitting new ones
- Added `is_delete_account` flag to pending_accounts table
- Modified account activation logic based on deletion status
- Enhanced error handling and user feedback during the approval process
1. Navigate to a company profile
2. Attempt to delete the company
3. Verify the deletion request is sent for approval
4. Check admin approval panel for the pending deletion request
5. Approve/reject the request and verify the company status updates accordingly
6. Try submitting multiple requests …

feat(accounts): implement pending delete request workflow

---

src/components/billing-statement/billing-statement-modal.tsx
src/types/database.types.ts
supabase/migrations/20241103014212_add_pending_billing_statements_table.sql

Added approval workflow for billing statements by creating a pending statements table and updating the creation/update flow.
- Created new `pending_billing_statements` table to handle approval workflow
- Modified billing statement modal to insert into pending table instead of direct creation
- Updated success messages to reflect pending approval status
- Added operation type tracking to distinguish between insert and update requests
- Implemented row-level security policies for the pending table
- Added user tracking for pending statement requests
1. Create a new billing statement
2. Verify the success message indicates pending approval
3. Update an existing billing statement
4. Confirm the update message indicates pending approval
5. Check that only finance department users can access …

feat(billing): implement pending billing statement approval workflow

---

src/app/(dashboard)/admin/approval-request/billing-statements/billing-statement-action-button.tsx
src/app/(dashboard)/admin/approval-request/billing-statements/billing-statement-info.tsx

Added approval/rejection functionality for billing statements in the admin dashboard.
- Created a new `BillingStatementActionButton` component that handles the approval/rejection logic
- Added approve and reject buttons to the billing statement information modal
- Implemented loading states for the action buttons
- Added mutations to update billing statements and pending billing statements tables
1. Navigate to the admin dashboard's billing statement approval section
2. Open a billing statement's information modal
3. Click either the approve or reject button
4. Verify that the loading state is shown while processing
5. Confirm that success/error toasts appear appropriately
6. Check that the billing statement status updates correctly in both tables
To enable administrators to review and …

fix(pending-billing-statements): RLS for admin

---

src/app/(dashboard)/admin/approval-request/billing-statements/billing-statement-action-button.tsx

Added `is_active` flag to billing statement approval process
When approving a billing statement, the `is_active` flag is now set to true alongside the `is_approved` flag. When rejecting, both flags are set to false.
1. Navigate to the admin billing statement approval page
2. Select a pending billing statement
3. Approve the statement
4. Verify that both `is_approved` and `is_active` flags are set to true
5. Reject another statement
6. Verify both flags are set to false
To ensure billing statements are properly activated when approved and deactivated when rejected, maintaining consistency in the billing statement lifecycle management.

TIM-588 feat(billing-statements): add reject billing-statements approval

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(billing statements)/billing-statements.tsx
src/app/(dashboard)/admin/approval-request/billing-statements/billing-statement-action-button.tsx
src/app/(dashboard)/admin/approval-request/billing-statements/pending-billing-statements-column.tsx
src/components/billing-statement/billing-statement-modal.tsx
src/components/billing-statement/delete-billing-statement.tsx
src/queries/ get-pending-billing-statements.ts
src/types/database.types.ts

Added support for deleting billing statements through the approval request workflow.
- Added `billing_statement_id` field to pending billing statements table
- Modified delete functionality to create a pending request instead of direct deletion
- Added OR Number column to pending billing statements table
- Updated billing statement action button to handle deletion requests
- Fixed ID reference in billing statement actions from `id` to `billing_statement_id`
1. Navigate to the billing statements section
2. Attempt to delete a billing statement
3. Verify the deletion request appears in the pending approval queue
4. Approve/reject the deletion request
5. Confirm the billing statement is properly deactivated upon approval
To ensure billing statement deletions go through the same approval …

feat(billing): implement billing statement delete request workflow

---

src/components/billing-statement/billing-statement-modal.tsx

Fixed billing statement ID handling during form submission
Modified the form submission logic to properly include the original billing statement ID when updating existing records. The ID is now conditionally spread into the submission data using the property name `billing_statement_id`.
1. Open an existing billing statement
2. Make modifications to any field
3. Save the changes
4. Verify that the update is successful and the existing record is modified rather than creating a new one
Previously, updates to existing billing statements weren't properly maintaining their ID reference, which could lead to duplicate records or failed updates. This change ensures the correct billing statement is updated by maintaining the ID relationship during form submission.

TIM-594 feat(billing-statements): add edit billing statements approval

---

src/app/(dashboard)/(home)/accounts/request/account-request-list-item.tsx
src/app/(dashboard)/(home)/billing-statements/data-table.tsx
src/app/(dashboard)/(home)/billing-statements/request/billing-request-list-item.tsx
src/app/(dashboard)/(home)/billing-statements/request/billing-request-list.tsx
src/app/(dashboard)/(home)/billing-statements/request/billing-statement-request.tsx

Added a request management system for billing statements and refactored operation type badges into a reusable component.
- Created a new billing statement request management interface
- Added a dialog to display pending billing statement requests
- Implemented a request list component to show pending billing statements with their operation types
- Extracted operation type badge logic into a reusable component
- Added a counter to show the number of pending requests
1. Navigate to the billing statements page
2. Look for the "X Requests" button at the top of the table
3. Click the button to open the dialog
4. Verify that pending requests are displayed with:
- Operation type badge (Add/Edit/Delete)
- Company name and OR number
- Time since creation
5. Verify that the request count updates …

feat(billing): add pending billing statement request list

---

src/app/(dashboard)/(home)/billing-statements/request/billing-request-list-item.tsx
src/app/(dashboard)/(home)/billing-statements/request/delete-billing-request.tsx
supabase/migrations/20241103064429_add_rls_for_update_on_pending_billing_statments.sql

Added ability for users to delete pending billing statement requests and implemented corresponding RLS policies.
- Created a new `DeleteBillingRequest` component with confirmation dialog
- Added a delete button to the billing request list item
- Added a `billing_statement_id` column to pending_billing_statements table
- Implemented RLS policies for insert, read, and update operations on pending_billing_statements
1. Log in as a finance user
2. Navigate to billing statements
3. Locate a pending billing request
4. Click "Cancel" button
5. Confirm deletion in the confirmation dialog
6. Verify the request is removed from the list
To allow users to cancel their pending billing statement requests if they were submitted in error or are no longer needed, while ensuring proper access controls …

feat(billing): add delete request functionality for pending statements

---

supabase/migrations/20241103123506_remove_rls_access_to_employees_on_billing_statements_table.sql

Restricted billing statements access to admin users only by removing finance department permissions.
- Removed existing RLS policies that allowed both admin and finance department users to insert and update billing statements
- Created new policies that exclusively grant insert and update permissions to admin department users
- Maintained the same policy structure but narrowed down the department check to 'admin' only
1. Log in as an admin user and verify you can still insert and update billing statements
2. Log in as a finance department user and confirm you can no longer insert or update billing statements
3. Attempt to create and modify billing statements with both user types to ensure proper access control
To enhance security by limiting billing statement modifications to admin users …

feat(billing): restrict billing statements RLS to admin only

---

package.json
pnpm-lock.yaml
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-form.tsx
src/types/database.types.ts
supabase/migrations/20241103131928_add_pending_company_employees_table.sql

Added pending employee management functionality with approval workflow
- Created new `pending_company_employees` table in the database
- Added UUID package for batch operation tracking
- Modified employee form to submit to pending table instead of direct updates
- Implemented operation tracking (insert/update) for employee changes
- Added row-level security policies for pending employee management
1. Create a new employee through the employee form
2. Verify the entry appears in the `pending_company_employees` table
3. Update an existing employee and confirm it creates a pending record
4. Verify that only authorized users (admin, marketing, finance, after-sales, under-writing) can access pending records
5. Confirm that users can only view their own pending submissions
To implement an …

feat(employees): add pending employee request workflow

---

src/app/(dashboard)/admin/approval-request/billing-statements/billing-statement-info.tsx
src/app/(dashboard)/admin/approval-request/company-employees/page.tsx
src/app/(dashboard)/admin/approval-request/company-employees/pending-company-employees-table.tsx
src/app/(dashboard)/admin/approval-request/company-employees/pending-employee-info.tsx
src/app/(dashboard)/admin/approval-request/company-employees/pending-employee-provider.tsx
src/app/(dashboard)/admin/approval-request/company-employees/pending-employees-row.tsx

Added employee details modal and improved table functionality for pending company employees approval requests.
- Enabled the operation badge in billing statement info
- Added a new modal dialog to display detailed employee information
- Implemented context provider for managing employee selection state
- Added search and pagination functionality to the pending employees table
- Created click handler to view employee details when clicking table rows
1. Navigate to the pending company employees approval page
2. Verify search functionality works in the table
3. Test pagination controls
4. Click on any employee row to open the details modal
5. Confirm all employee information is displayed correctly
6. Verify approve/reject buttons are present
7. Check that the operation badge displays …

feat(employees): implement pending employee approval details view

---

src/app/(dashboard)/admin/approval-request/company-employees/employee-action-button.tsx
src/app/(dashboard)/admin/approval-request/company-employees/pending-company-employees-columns.tsx
src/app/(dashboard)/admin/approval-request/company-employees/pending-employee-info.tsx
src/queries/get-pending-company-employees.ts

Added approval/rejection functionality for pending company employee requests.
- Created new `EmployeeActionButton` component to handle approve/reject actions
- Updated pending employee info modal to include action buttons with loading states
- Reordered employee name columns to show last name before first name
- Added user_id to created_by query for proper employee creation tracking
2. Select a pending company employee request
3. Click either "Approve" or "Reject" in the modal
4. Verify that:
- Loading state is shown during action
- Success/error toast appears after action
- Modal closes on successful action
- Employee data is properly created/updated in database
To implement the core functionality for administrators to process pending …

feat(employees): implement employee approval/reject workflow

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-data-table.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/request/employee-request-list-item.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/request/employee-request-list.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/request/employee-request.tsx
src/app/(dashboard)/(home)/billing-statements/data-table.tsx
src/queries/get-pending-employee-by-company-id.ts

Added a new employee request feature to display and manage pending employee submissions.
- Added a new employee request button that shows the count of pending requests
- Created a dialog component to display pending employee submissions
- Implemented list view for pending employee requests showing operation type and submission time
- Added query functionality to fetch pending employees by company ID
1. Navigate to the employees table view
2. Look for the "Requests" button showing the count of pending submissions
3. Click the button to open the dialog
4. Verify that pending employee submissions are displayed with their operation type and submission time
5. Confirm that the request count updates when new submissions are added or approved
To provide users with a streamlined way to view and …

feat(employees): add pending employee request list and view

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-form.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/request/delete-employee-request.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/request/employee-request-list-item.tsx

Added functionality to delete pending employee requests and reorganized employee form imports.
- Created a new `DeleteEmployeeRequest` component with confirmation dialog
- Added delete functionality to employee request list items
- Implemented toast notifications for successful/failed deletions
- Reorganized imports in the employee form for better code organization
1. Navigate to the employee requests section
2. Locate any pending employee request
3. Click the "Cancel" button
4. Confirm deletion in the confirmation dialog
5. Verify the toast notification appears
6. Confirm the request is removed from the list
To provide administrators the ability to remove pending employee requests that are no longer needed, improving user management capabilities and maintaining data cleanliness in the …

feat(employees): add delete request functionality for pending employees

---

supabase/migrations/20241104034008_remove_rls_access_to_employee_table_for_employees.sql

Restricted employee table access by removing existing RLS policies and implementing more specific access controls.
- Removed three existing RLS policies for company employees table
- Added new RLS policy for read access that excludes agents
- Created admin-specific update policy for company employees
- Implemented policy for pending company employees that allows updates only by the creator when not approved
1. Login as an agent and verify they cannot access company employees
2. Login as admin and confirm they can update company employee records
3. Login as non-admin department user and verify they can only read company employee data
4. Test pending company employees updates:
- Verify only creator can update their pending records
- Confirm updates only work when record is not approved
- …

feat(employees): restrict employee table RLS to admin

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/import-employees.tsx
src/app/(dashboard)/admin/approval-request/company-employees/groupData.ts
src/app/(dashboard)/admin/approval-request/company-employees/pending-company-employees-columns.tsx
src/app/(dashboard)/admin/approval-request/company-employees/pending-company-employees-table.tsx

Added batch processing functionality for employee imports and enhanced the pending employees approval table UI.
- Implemented batch grouping for imported employees using a shared batch ID
- Added a "Batch" badge indicator for grouped employee records
- Updated the pending employees table to display the number of employees in a batch
- Modified column headers and display logic for first name and surname fields
- Introduced a new `groupData` utility function to organize employee records by batch
1. Import multiple employees at once through the employee import feature
2. Navigate to the admin approval request page
3. Verify that batch imports are grouped together with a "Batch" badge
4. Confirm that the number of employees in each batch is displayed correctly
5. Check that single employee …

feat(employees): implement batch import grouping in approval list

---

src/app/(dashboard)/(home)/accounts/data-table.tsx
src/app/(dashboard)/(home)/accounts/export-requests/export-accounts-modal.tsx
supabase/migrations/20241104150917_add_policy_for_users_on_export_table.sql

YAYYYYY
Added functionality to submit export requests for accounts data through a modal interface.
- Added export type parameter to `ExportAccountsModal` component
- Implemented Supabase integration for submitting export requests
- Added success and error toast notifications
- Included loading state handling for the confirm button
- Connected the export request to the authenticated user
2. Click the export button to open the modal
3. Click confirm to submit an export request
4. Verify that a success toast appears
5. Verify the request appears in the `pending_export_requests` table
6. Test error handling by disconnecting from the database and attempting an export
To provide users with a secure way to request data exports while maintaining control over data …

TIM-622 Submission for backend

---

src/app/(dashboard)/admin/approval-request/company-employees/information/batch-employee.tsx
src/app/(dashboard)/admin/approval-request/company-employees/information/employee-information.tsx
src/app/(dashboard)/admin/approval-request/company-employees/information/pending-employee-info.tsx
src/app/(dashboard)/admin/approval-request/company-employees/page.tsx

Added support for batch employee approval requests in the admin dashboard
- Created new components to handle batch employee information display
- Split employee information display into separate components for single and batch views
- Added badges to indicate batch requests and employee count
- Implemented scrollable view for batch employee data
- Reorganized file structure for better component organization
1. Navigate to the admin approval request dashboard
2. Select a batch employee request from the pending list
3. Verify that multiple employees are displayed with a scrollable interface
4. Confirm that batch indicators and employee count are visible
5. Test both single and batch employee request views
6. Verify all employee information fields are displayed correctly
To support the …

feat(employees): add batch employee approval request view

---

src/app/(dashboard)/admin/approval-request/company-employees/employee-action-button.tsx
src/app/(dashboard)/admin/approval-request/company-employees/information/batch-employee.tsx

Enhanced employee approval functionality to support both single and batch employee operations.
- Modified the employee action button to handle both individual and batch employee approvals
- Updated the upsert mutation logic to process multiple employees simultaneously
- Added comprehensive error handling for both employee creation and status updates
- Removed console.log statement from batch employee component
- Included additional employee data fields in the upsert operation
1. Navigate to the admin approval request section
2. Test single employee approval:
- Select an individual employee
- Click approve/reject button
- Verify employee status updates correctly
2. Test batch employee approval:
- Select a batch of employees
- Click approve/reject button
- Verify all employees in batch are …

feat(employees): implement batch employee approval handling

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/import-employees.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/themeOverrides.ts

Added theme customization to the employee import spreadsheet component
- Created a new `themeOverrides.ts` file with comprehensive theme configurations
- Updated the `ImportEmployees` component to use the custom theme
- Added conditional rendering to prevent unnecessary component mounting
- Implemented styling for data grid, modals, buttons, and various UI components
1. Navigate to the employee import section
2. Open the import modal
3. Verify the new styling matches the design system:
- Check modal appearance and borders
- Verify data grid styling and borders
- Confirm button colors and interactions
- Validate text colors and typography
To align the import spreadsheet component with the application's design system and improve visual consistency. The default styling of the React …

feat(employees): add theme overrides for import modal

---

src/app/(dashboard)/(home)/accounts/loading.tsx

Added a loading state component for the Accounts page
Created a new loading component that displays a skeleton UI while the Accounts page data is being fetched. The component includes a page header with the "Accounts" title and a skeleton loader for additional content.
1. Navigate to the Accounts page
2. Verify that the loading state appears momentarily before the full content loads
3. Ensure the skeleton UI matches the layout of the actual content
4. Test with slow network conditions to better observe the loading state
To improve user experience by providing visual feedback during data loading, preventing a blank screen and reducing perceived loading times. This follows best practices for progressive loading and maintains visual consistency with the rest of the application.

feat(accounts): add loading state component

---

src/app/(dashboard)/admin/approval-request/accounts/loading.tsx

Added a loading state component for the account approval page in the admin dashboard.
Created a new loading component that displays a skeleton UI while the account approval page loads. The component includes a page header with a "Pending Accounts" title and a skeleton placeholder for additional content.
1. Navigate to the admin dashboard's account approval page
2. Verify that the loading state appears momentarily before the main content loads
3. Confirm the skeleton UI matches the layout of the actual content
To improve user experience by providing visual feedback during data loading, preventing a blank screen and reducing perceived loading times. This follows best practices for progressive loading states in React applications.

feat(admin): add loading state for account approval page

---

src/app/(dashboard)/admin/types/edit/edit-type-fields.tsx
src/app/(dashboard)/admin/types/edit/edit-type.tsx
src/app/(dashboard)/admin/types/loading.tsx
src/app/(dashboard)/admin/types/type-list.tsx

Split the edit type form into a separate component and added dynamic loading capabilities.
- Created a new `EditTypeFields` component to handle the form fields and submission
- Implemented dynamic loading using `next/dynamic` for the edit form
- Added a loading state component for the types page
- Moved edit-related components to a dedicated `/edit` directory
1. Navigate to the admin types page
2. Click the edit button on any type
3. Verify the edit form loads dynamically
4. Confirm the loading state appears while the form is being loaded
5. Test that editing a type name still functions correctly
This change improves the application's performance by implementing code splitting and lazy loading for the edit form component. The separation of concerns also makes the code more maintainable …

feat(types): implement dynamic type editing component

---

src/app/(dashboard)/admin/logs/loading.tsx

Added a loading state component for the Activity Logs admin page.
Created a new loading component that displays a placeholder layout while the Activity Logs page data is being fetched. The component includes a responsive sidebar with the "Activity Logs" heading.
1. Navigate to the admin/logs page
2. Verify that the loading state appears briefly before the main content loads
3. Test responsiveness by viewing on different screen sizes (mobile, tablet, desktop)
4. Confirm the transition animations work smoothly
To improve user experience by providing visual feedback during data loading, preventing layout shifts, and maintaining a consistent UI structure throughout the loading process.

feat(admin): add loading state for activity logs

---

src/app/(dashboard)/(home)/(dashboard)/loading.tsx

Added a loading state component for the dashboard home page.
Created a new loading component that displays a page title with "Mock Dashboard" text while the main dashboard content is being loaded.
1. Navigate to the dashboard home page
2. Verify that the loading state appears momentarily before the main content loads
3. Confirm the loading state shows "Mock Dashboard" title and "Welcome to the dashboard" description
To improve user experience by providing visual feedback during the dashboard loading process, preventing a blank screen while content is being fetched or rendered.

feat(dashboard): add loading state component

---

src/app/layout.tsx

Switched from Geist Sans to Inter font for the application's typography.
- Replaced Geist Sans with Inter font from Google Fonts
- Added Inter font configuration with Latin subset support
- Updated the font variable naming to `--font-sans`
- Reorganized imports for better code organization
1. Run the application locally
2. Verify that the Inter font is properly loaded and applied across all text elements
3. Ensure the font renders correctly across different browsers and devices
4. Confirm that the Latin character subset displays properly
Inter is a highly readable, open-source font designed specifically for computer screens. It provides better accessibility and consistent rendering across different platforms while being freely available through Google Fonts, reducing external dependencies …

feat(layout): replace Geist with Inter font

---

package.json
pnpm-lock.yaml
src/app/(dashboard)/(home)/(dashboard)/client-acquisition/chart-config.ts
src/app/(dashboard)/(home)/(dashboard)/client-acquisition/client-acquisition-card.tsx
src/app/(dashboard)/(home)/(dashboard)/client-acquisition/client-acquisition-chart.tsx
src/app/(dashboard)/(home)/(dashboard)/page.tsx
src/app/globals.css
src/components/ui/card.tsx
src/components/ui/chart.tsx
supabase/seed.sql

Added an accounts acquisition chart to visualize new account growth over the past 12 months.
- Added a new chart component using Recharts library
- Created a client acquisition card and chart to display account growth trends
- Added chart styling variables and configuration
- Implemented data fetching from Supabase to populate the chart
- Modified seed data to include timestamps for better data visualization
- Added chart-related UI components and styling utilities
1. Run the application and navigate to the dashboard
2. Verify the accounts acquisition chart appears
3. Hover over data points to see monthly account creation totals
4. Confirm the chart displays data for the last 12 months
5. Check that the tooltip shows correct monthly values
6. Verify the chart styling matches the …

feat(dashboard): add client acquisition chart

---

src/app/(dashboard)/(home)/accounts/columns/accounts-columns.tsx
src/components/active-badge.tsx
src/queries/get-accounts.ts
src/types/database.types.ts
supabase/migrations/20241107024658_add_is_account_active_column_on_accounts.sql

Added an account status indicator to display whether accounts are active or inactive.
- Added a new `is_account_active` boolean column to the accounts table
- Created a new `ActiveBadge` component that displays a colored badge indicating active/inactive status
- Added a new column to the accounts table UI that shows the active status using the badge
- Updated database types to include the new `is_account_active` field
- Modified the accounts query to fetch the new status field
1. Run the new migration to add the `is_account_active` column
2. Navigate to the accounts table
3. Verify that each account row displays either a green "Active" badge or a red "Inactive" badge
4. Update an account's active status in the database and confirm the badge updates accordingly
To provide clear visual …

feat(accounts): add active status badge and column

---

src/app/(dashboard)/(home)/(dashboard)/page.tsx
src/app/(dashboard)/(home)/(dashboard)/retention-rate/chart-config.ts
src/app/(dashboard)/(home)/(dashboard)/retention-rate/retention-rate-card.tsx
src/app/(dashboard)/(home)/(dashboard)/retention-rate/retention-rate-chart.tsx

Added a new Retention Rate card component to the dashboard that displays client retention metrics in a radial chart format.
- Created a new RetentionRateCard component with a radial chart visualization
- Added chart configuration for retention rate display
- Implemented retention rate calculation logic using account data from Supabase
- Integrated the new card into the dashboard layout
1. Navigate to the dashboard page
2. Verify the Retention Rate card appears with a radial chart
3. Confirm the retention rate percentage is calculated correctly based on:
- Active clients at period end
- Clients at period start
- New clients during the period
4. Check that the date range displays correctly (last 12 months)
5. Verify the chart updates when account data changes
This addition provides valuable …

TIM-677 feat(home): add retention rate chart

---

package.json
pnpm-lock.yaml
src/app/(dashboard)/(home)/(dashboard)/loading.tsx
src/app/(dashboard)/(home)/(dashboard)/page.tsx
src/app/(dashboard)/(home)/(dashboard)/retention-rate/retention-rate-chart.tsx
src/app/(dashboard)/(home)/(dashboard)/top-agents/top-agents-card.tsx
src/app/(dashboard)/(home)/(dashboard)/top-agents/top-agents-list.tsx
src/app/(dashboard)/admin/agents/agents-list.tsx
src/components/ui/avatar.tsx

Added a new Top Agents card to the dashboard displaying the most active agents over the last 12 months.
- Added a new Top Agents card component showing the top 5 performing agents
- Integrated react-nice-avatar for agent avatars
- Added Radix UI Avatar component
- Updated dashboard title from "Mock Dashboard" to "Dashboard"
- Removed duplicate PreviousStatement components
1. Navigate to the dashboard
2. Verify the Top Agents card appears with a list of agents
3. Confirm each agent displays:
- Ranking number (1-5)
- Avatar
- Full name
- Number of clients acquired in the last 12 months
4. Verify the data sorts correctly by number of clients
This addition provides valuable visibility into agent performance, helping identify and recognize top performers based on client acquisition metrics. …

feat(dashboard): add top agents leaderboard card

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-about.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-edit-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-page.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/delete/company-delete-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/delete/company-delete-form.tsx

Enhanced company account deletion functionality and improved pending request handling
- Relocated delete button to bottom of company profile and updated its styling
- Added user role validation for delete button visibility
- Improved pending request checks to use `maybeSingle()` instead of `single()`
- Added validation to ensure users can't create duplicate pending requests
- Prevented delete button from showing during edit mode
- Added user authentication check before processing delete requests
1. Log in with different user roles to verify delete button visibility
2. Attempt to delete a company account and verify the confirmation modal
3. Try creating multiple delete requests to ensure duplicates are prevented
4. Verify delete button is hidden during edit mode
5. Test with an …

feat(accounts): improve company delete functionality and UI

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-data-table.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-requests-list-item.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-requests.tsx
src/queries/get-pending-employee-exports.tsx

YAYYYYY
Added an export requests button and counter to track pending employee export requests.
- Added a new `EmployeeExportRequests` component to display pending export requests
- Created a new query `getPendingEmployeeExports` to fetch pending export request counts
- Updated the employees data table to show both employee requests and export requests side by side
- Added a new list item component for export requests
1. Navigate to the employees data table
2. Verify that both "Employee Requests" and "Export Requests" buttons are visible
3. Confirm that the count on each button reflects the correct number of pending requests
4. Click on "Export Requests" to verify the modal opens and displays pending export requests
To provide users with visibility into pending export requests and improve …

TIM-664 Add requests on requests tab for employee exports

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-request-list.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-requests-list-item.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-requests.tsx
src/queries/get-pending-employee-exports.tsx

I'm tired i hate backend dev >:(
Added functionality to display pending employee export requests with user details and timestamps.
- Created a new employee export request list component to display pending exports
- Enhanced the export request list item to show requester's name and time since request
- Updated the pending employee exports query to fetch additional user details
- Integrated the export request list into the export requests dialog
1. Navigate to the employee section
2. Click on "Export Requests" button
3. Verify that pending export requests are displayed with:
- Requester's full name
- Time since request was made
4. Confirm that the count of pending requests is accurate
To provide users with visibility into pending export requests and their status, allowing better tracking …

TIM-676 Add requests lists for employee requests tab

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/fields.ts
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/parseDate.ts

Added support for additional date formats and case-insensitive gender/marital status matching in employee import functionality.
- Added uppercase variants for gender options (MALE, FEMALE)
- Added uppercase variants for marital status options (SINGLE, MARRIED, DIVORCED, WIDOWED)
- Enhanced date parsing to support:
- Single-digit month format (e.g., 1/02/2024)
- Date range exclusion (e.g., "1/1/2024 to 1/2/2024")
1. Import employee data with:
- Uppercase gender values (MALE, FEMALE)
- Uppercase marital status values (SINGLE, MARRIED, etc.)
- Dates in single-digit month format (1/02/2024)
- Date ranges to verify they're not incorrectly parsed
2. Verify all values are correctly imported and formatted
To improve data import flexibility by accommodating more common data formats and variations …

feat(import): improve date parsing and case matching

---

src/app/(dashboard)/(home)/accounts/columns/accounts-columns.tsx

Added accessor function for company address column in accounts table
Added an `accessorFn` to properly handle and display company addresses in the accounts table, including fallback to empty string when address is undefined
1. Navigate to the accounts table
2. Verify company addresses are displayed correctly
3. Check that empty/undefined addresses show as blank cells instead of errors
To prevent potential rendering issues when company addresses are undefined and ensure consistent display of address data in the accounts table

feat(accounts): add company address accessor

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-actions-dropdown.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-data-table.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-modal.tsx
src/assets/icons/ellipsis-vertical.tsx

Replaced employee action buttons with a dropdown menu for better UI organization.
- Created a new `EmployeeActionsDropdown` component with a vertical ellipsis menu
- Moved "Add Employee" and "Export Employees" actions into the dropdown menu
- Added a new `EllipsisVertical` icon component
- Updated the `EmployeeExportModal` to accept a custom button prop for flexibility
- Replaced the standalone action buttons in the employees data table with the new dropdown
1. Navigate to the employees table view
2. Verify the vertical ellipsis menu appears in the top right
3. Click the menu and confirm both "Add Employee" and "Export Employees" options are present
4. Test each action to ensure they function as expected:
- Adding a new employee
- Exporting employee data
This change improves the UI by …

feat(employees): add actions dropdown menu

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/request/clear-employee-requests.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/request/delete-employee-request.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/request/employee-request.tsx

Added functionality to clear all employee requests in bulk and improved request deletion tracking.
- Created new `ClearEmployeeRequests` component with confirmation dialog
- Added `updated_at` timestamp tracking for request deletions
- Integrated bulk clear functionality in the employee requests dialog
- Added disable state for clear button when no requests exist
1. Navigate to employee requests dialog
2. Verify "Clear Requests" button appears in dialog header
3. Click "Clear Requests" to see confirmation prompt
4. Confirm deletion to remove all pending requests
5. Verify toast notification appears on successful deletion
6. Check that button is disabled when no requests exist
To provide administrators with an efficient way to manage employee requests by allowing them to clear multiple …

TIM-685 feat(employees): add clear all employees

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-actions-dropdown.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-information/delete-all-employees.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-data-table.tsx
src/app/(dashboard)/admin/approval-request/company-employees/employee-action-button.tsx
src/app/(dashboard)/admin/approval-request/company-employees/groupData.ts
supabase/migrations/20241110091956_add_RLS_for_admin_to_employees_table.sql

Added functionality to delete all employees in bulk through a new dropdown action, with admin approval workflow.
- Added "Delete All Employees" option to the employee actions dropdown
- Created new component to handle bulk employee deletion requests
- Implemented batch processing for employee deletion requests
- Added RLS policy to allow admin users to update employee records
- Enhanced approval workflow to handle bulk employee deletions
- Updated employee action handling to support is_active status changes
1. Navigate to the employees page
2. Click the actions dropdown menu
3. Select "Delete All Employees"
4. Confirm the deletion request
5. Login as admin to verify the deletion request appears in the approval queue
6. Approve/reject the deletion request
7. Verify employees are marked as …

feat(employees): add bulk delete functionality

---

src/app/(dashboard)/admin/approval-request/accounts/page.tsx
src/app/(dashboard)/admin/approval-request/billing-statements/page.tsx
src/app/(dashboard)/admin/approval-request/company-employees/page.tsx

Added page titles to admin approval request pages
Added metadata exports to set page titles for:
- Review Accounts
- Review Billing Statements
- Review Employees
1. Navigate to each admin approval request page:
- `/admin/approval-request/accounts`
- `/admin/approval-request/billing-statements`
- `/admin/approval-request/company-employees`
2. Verify that the browser tab displays the correct page title for each page
Improves user experience by providing clear page titles in browser tabs, making it easier for administrators to identify different approval request pages when multiple tabs are open

feat(admin): add page titles to approval request views

---

src/components/layout/navigation/navigation-item.tsx
src/components/layout/navigation/sub-navigation-item.tsx

Added mobile sidebar auto-close functionality when navigating between pages
- Imported and implemented `useSidebar` hook in navigation components
- Added `onClick` handlers to navigation links that close the mobile sidebar when clicked
- Applied changes to both main navigation items and sub-navigation items
1. Open the application on a mobile device or using mobile device emulation
2. Open the mobile sidebar
3. Click on any navigation link
4. Verify that the sidebar automatically closes when navigating to a new page
Improves the mobile user experience by automatically closing the sidebar after navigation, preventing it from remaining open and obscuring the new page content

feat(navigation): close mobile sidebar on link click

---

src/app/(dashboard)/admin/approval-request/accounts/approval-request-info.tsx

Added scrolling and adjusted width constraints for the account approval request modal
- Modified the dialog content's maximum width from `max-w-6xl` to `sm:max-w-4xl`
- Added `max-h-[90vh]` to limit the modal height to 90% of the viewport
- Implemented `overflow-y-auto` to enable vertical scrolling when content exceeds the height limit
1. Navigate to the admin approval request section
2. Open an account approval request modal
3. Verify that:
- The modal is slightly narrower than before
- Content scrolls vertically if it exceeds the viewport height
- Modal height doesn't exceed 90% of the screen
To improve the user experience by ensuring the modal content remains accessible on smaller screens and preventing it from extending beyond comfortable viewing limits. The scrollable content area …

fix(admin): adjust approval request modal dimensions

---

src/app/(dashboard)/(home)/(dashboard)/client-acquisition/client-acquisition-chart.tsx

Fixed a React hooks dependency warning in the client acquisition chart component.
Removed `rerender` from the useEffect dependency array and added an ESLint disable comment to suppress the hooks exhaustive deps warning.
1. Navigate to the client acquisition chart
2. Verify the chart still updates correctly when data changes
3. Check browser console to confirm no React hooks dependency warnings
The `rerender` dependency was causing unnecessary re-renders and wasn't actually needed for the chart's functionality. This change improves performance while maintaining the same behavior.

fix(home): rerender error

---

src/app/(dashboard)/admin/approval-request/employee-exports/employee-export-requests-columns.tsx
src/app/(dashboard)/admin/approval-request/employee-exports/employee-export-requests-rows.tsx
src/app/(dashboard)/admin/approval-request/employee-exports/employee-exports-requests-table.tsx
src/queries/get-all-pending-employee-exports.ts

Added a new employee export requests table with sorting, filtering, and pagination capabilities.
- Created new table columns for displaying account name, requester, and request timestamp
- Implemented table rows component with proper cell rendering
- Added table pagination and sorting functionality
- Enhanced the export requests query to include company name information
- Integrated table components into the main employee exports request view
1. Navigate to the admin approval request section
2. View the employee exports table
3. Verify that:
- Account names, requesters, and timestamps are displayed correctly
- Sorting works on all columns
- Pagination controls function properly
- "No results" message appears when table is empty
To provide administrators with a clear interface for managing …

TIM-699 Add table for employee exports

---

src/app/(dashboard)/admin/approval-request/account-exports/account-export-requests-table.tsx
src/app/(dashboard)/admin/approval-request/account-exports/page.tsx
src/queries/get-pending-account-exports.ts

Naintindihan ko na kung para san siya yehey
Added server-side prefetching and sorting functionality to account export requests.
- Implemented server-side data prefetching for account export requests using React Query
- Added sorting capability to pending account exports query with a default descending order
- Wrapped the account exports page with HydrationBoundary to prevent hydration issues
- Modified the query to support customizable sort direction (asc/desc)
1. Navigate to the account exports page
2. Verify that data loads immediately without loading states
3. Confirm that export requests are sorted by creation date in descending order
4. Check that the table maintains its state during page navigation
Server-side prefetching improves the initial page load experience by eliminating …

TIM-722 Add sorting on query for accounts and utilized prefetchQuery

---

src/app/(dashboard)/admin/approval-request/employee-exports/employee-exports-requests-table.tsx
src/app/(dashboard)/admin/approval-request/employee-exports/page.tsx
src/queries/get-all-pending-employee-exports.ts

Added sorting functionality to pending employee exports with default descending order by creation date.
- Added sorting parameter to `getAllPendingEmployeeExports` query
- Implemented default descending sort order by `created_at` field
- Added server-side prefetching for employee exports data
- Integrated React Query's hydration boundary for better data handling
1. Navigate to the employee exports approval request page
2. Verify that requests are sorted by creation date in descending order (newest first)
3. Confirm that the data is properly hydrated and displayed without loading flickers
4. Verify that the sorting functionality works correctly when changed
To improve user experience by displaying the most recent export requests first and implement proper server-side data fetching with …

TIM-725 Add sorting on query for employee exports and utilized ss prefetching

---

src/app/(auth)/confirm-account/set-password-form.tsx
src/app/(dashboard)/admin/users/edit/edit-user-form.tsx

Added error handling for password confirmation page and temporarily disabled email confirmation in user edit form.
- Added URL parameter checking for error codes in the password confirmation page
- Implemented error message display for 4xx errors during password confirmation
- Commented out the `<ConfirmEmail>` component in the user edit form
1. Attempt to confirm a password with an invalid token/link
2. Verify that appropriate error messages are displayed for 4xx errors
3. Navigate to the user edit form and confirm that email confirmation option is not visible
To improve user experience by providing clear feedback when password confirmation fails and temporarily disable email confirmation functionality while updates are being made to the system.

feat(accounts): remove resending of email

---

src/components/billing-statement/delete-billing-statement.tsx

Added validation to prevent duplicate delete requests for billing statements
- Added a check to verify if a pending delete request already exists for a billing statement
- Implemented error handling with toast notifications for duplicate requests
- Wrapped the delete operation in a try-catch block for better error management
- Removed unnecessary fragment wrapper around the delete button
1. Navigate to a billing statement
2. Click the delete button
3. Verify that you cannot submit multiple delete requests for the same billing statement
4. Confirm that an error toast appears when attempting to create duplicate requests
5. Verify that the delete operation still works when there are no pending requests
To prevent duplicate delete requests from being created for the same billing statement, …

feat(billing): prevent duplicate delete requests

---

supabase/migrations/20241111123922_rls_update_on_employees.sql

Added RLS policy to control employee updates based on user permissions and department roles.
Created a new Row Level Security (RLS) policy for the `pending_company_employees` table that allows updates only when:
- The authenticated user is the creator of the record
- The employee record is not yet approved
- The user belongs to specific departments (admin, marketing, finance, after-sales, or under-writing)
1. Log in as a user from one of the allowed departments
2. Attempt to update a pending employee record you created
3. Verify update succeeds
4. Try updating an approved record or one created by another user
5. Verify update fails
6. Test with a user from an unauthorized department
7. Verify update fails
To implement proper access control ensuring only authorized personnel from specific …

feat(employees): add RLS policy for pending updates

---

src/app/(dashboard)/admin/approval-request/account-exports/account-export-request-modal.tsx
src/app/(dashboard)/admin/approval-request/account-exports/account-export-requests-columns.tsx
src/app/(dashboard)/admin/approval-request/account-exports/account-export-requests-provider.tsx
src/app/(dashboard)/admin/approval-request/account-exports/account-export-requests-rows.tsx
src/app/(dashboard)/admin/approval-request/account-exports/page.tsx

I used a context provider 
Added a modal dialog for handling account export request approvals with context management.
- Created a new modal component for displaying account export request details
- Implemented a context provider to manage the modal state and selected request data
- Added an actions column with a menu button to the export requests table
- Enhanced table rows with click handling to open the modal
- Connected the modal to display the requester's name and creation date
2. Click on any row in the account export requests table
3. Verify that the modal opens with the correct user details and creation date
4. Confirm that the modal can be closed
5. Check that the menu button appears in the actions column
To provide administrators …

TIM-630 Confirmation modal for account exports table

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/parseDate.ts

Simplified date parsing logic using `isValid` from date-fns library
Replaced complex regex date validation with `isValid` function from date-fns to determine if a string can be parsed as a valid date
1. Import data with various date formats (MM/dd/yyyy, dd MMM yyyy, M/dd/yyyy)
2. Verify dates are correctly parsed and formatted to MM/dd/yyyy
3. Ensure invalid date strings remain unchanged
The previous regex-based validation was overly complex and potentially brittle. Using `isValid` from date-fns provides a more reliable and maintainable way to validate dates while handling a wider range of valid date formats.

refactor(employees): simplify date parsing logic

---

src/app/(dashboard)/admin/approval-request/company-employees/information/batch-employee.tsx

Fixed birth date display in batch employee approval view
Updated the birth date field to correctly reference individual employee data instead of the parent selected data object
2. Select a batch of employees for approval
3. Verify that each employee's birth date is displayed correctly in their respective information sections
The birth date was previously referencing the parent selectedData object instead of the individual employee item, causing incorrect or missing birth date displays in the batch approval view. This fix ensures each employee's correct birth date is shown.

fix(admin): correct birth date display in batch employee view

---

src/components/table-header.tsx

Removed column hiding functionality from table headers and simplified the dropdown menu
- Removed the "Hide" option from column header dropdown menus
- Removed `EyeNoneIcon` import and related components
- Removed dropdown menu separator
- Reordered imports for better organization
1. Open any table with sortable columns
2. Click the dropdown menu in any column header
3. Verify only "Asc" and "Desc" sorting options are present
4. Confirm the column hiding functionality is no longer available
The column hiding functionality was determined to be unnecessary for the current use case, leading to a cleaner and more focused user interface. This simplification makes the table header interactions more straightforward and reduces potential user confusion.

refactor(table): remove column visibility toggle

---

src/app/(dashboard)/admin/approval-request/company-employees/employee-action-button.tsx

Updated success toast messages for employee approval/rejection actions to be more specific.
Modified the success toast notifications to dynamically display whether the request was approved or rejected, rather than using generic "Success" messaging.
2. Attempt to approve or reject an employee request
3. Verify the toast message displays the correct action (approved/rejected)
4. Confirm the toast description matches the action taken
To provide clearer feedback to administrators when they take action on employee requests, making it immediately obvious which action was successfully completed.

fix(admin): update approval request toast messages

---

src/app/(dashboard)/admin/approval-request/employee-exports/employee-export-requests-provider.tsx

Please check if im doing things right
Added a new context provider for managing employee export request states.
Created `EmployeeExportRequestsProvider` and its corresponding hook to manage modal state, loading state, and selected data for employee export requests. The provider exposes methods to control these states and makes them available throughout the component tree.
1. Import and wrap components that need access to employee export request states with `EmployeeExportRequestsProvider`
2. Use `useEmployeeExportRequestsContext` hook in child components
3. Verify that modal, loading states, and selected data can be accessed and modified
4. Ensure context throws an error when used outside of provider
To centralize the state management for employee export requests and provide a consistent …

TIM-728 Add a context provider for employee exports table

---

src/app/(dashboard)/admin/approval-request/employee-exports/employee-export-requests-columns.tsx
src/app/(dashboard)/admin/approval-request/employee-exports/employee-export-requests-modal.tsx
src/app/(dashboard)/admin/approval-request/employee-exports/employee-export-requests-rows.tsx
src/app/(dashboard)/admin/approval-request/employee-exports/employee-exports-requests-table.tsx
src/app/(dashboard)/admin/approval-request/employee-exports/page.tsx

Added a modal dialog for handling employee export request approvals and rejections.
- Added an actions column with a menu button to the employee export requests table
- Created a new modal component to display export request details
- Implemented context provider for managing modal state and selected data
- Connected row click handlers to open the modal with request information
- Switched from browser to server client for initial data fetching
1. Navigate to the employee export requests page
2. Click on any row in the table or the menu button
3. Verify that the modal opens with the correct request details
4. Confirm that the requester's name and creation date are displayed properly
5. Verify that the modal can be closed
To provide administrators with a clear interface for reviewing and …

TIM-727 feat: Confirmation modal for company employees

---

src/app/(dashboard)/admin/approval-request/account-exports/account-export-request-modal.tsx
src/app/(dashboard)/admin/approval-request/account-exports/account-export-requests-approval-button.tsx

Added approval and rejection functionality to the Account Export Request Modal
- Added approve and reject buttons to the Account Export Request Modal
- Created a new `AccountExportRequestsApprovalButton` component to handle approval/rejection logic
- Integrated loading states and success/error toasts for user feedback
- Connected the approval actions to the Supabase database
1. Navigate to the admin approval requests section
2. Open an account export request modal
3. Test the approve button:
- Click approve
- Verify success toast appears
- Confirm request status updates in database
4. Test the reject button:
- Click reject
- Verify success toast appears
- Confirm request is marked as rejected and inactive
To provide administrators with the ability to approve or reject account export …

TIM-729 Add approval buttons to account export request modal

---

src/app/(dashboard)/admin/approval-request/account-exports/account-export-request-modal.tsx
src/app/(dashboard)/admin/approval-request/components/export-requests-approval-button.tsx
src/app/(dashboard)/admin/approval-request/employee-exports/employee-export-requests-modal.tsx

Unified the export request approval functionality between account and employee exports.
- Renamed `AccountExportRequestsApprovalButton` to `ExportRequestsApprovalButton` and moved it to a shared components directory
- Added support for both account and employee export modal states in the approval button
- Implemented approval/reject buttons in the employee export requests modal
- Removed unused imports from account export request modal
1. Navigate to the admin approval request section
2. Test account export approval/rejection:
- Open an account export request
- Click approve/reject buttons
- Verify modal closes and status updates
3. Test employee export approval/rejection:
- Open an employee export request
- Click approve/reject buttons
- Verify modal closes and status updates
To reduce …

TIM-730 Refactor export request approval buttons and add to employee exports

---

src/app/(dashboard)/(home)/(dashboard)/retention-rate/retention-rate-card.tsx
src/app/(dashboard)/(home)/(dashboard)/retention-rate/retention-rate-chart.tsx
src/types/database.types.ts
src/utils/retentionRate.ts
supabase/migrations/20241112121323_add_account_status_changes_table.sql
supabase/seed.sql

Improved retention rate calculation accuracy by tracking account status changes over time.
- Created new `account_status_changes` table to track historical account status
- Added database trigger to log status changes automatically
- Implemented `calculateRetentionRate` utility function for precise calculations
- Updated retention rate display period from 12 months to 1 month
- Modified seed data to populate historical status changes
1. Run database migrations to create the new table and trigger
2. Execute seed data to populate historical account changes
3. Verify retention rate calculation in dashboard
4. Toggle account status and confirm changes are logged
5. Check that retention rate updates accordingly
The previous implementation only considered current account status, which didn't …

refactor(retention): improve rate calculation accuracy

---

src/app/(dashboard)/(home)/file-manager/account-downloads.tsx
src/app/(dashboard)/(home)/file-manager/downloadable-files.tsx
src/app/(dashboard)/(home)/file-manager/employee-downloads.tsx
src/app/(dashboard)/(home)/file-manager/page.tsx
src/components/layout/navigation/navigation.tsx

Added a new file manager section to download account and employee files
- Created a new file manager page with downloadable files interface
- Added file download components for both account and employee files
- Introduced a new navigation item under "File Manager" section
- Each download component displays an XLS file icon with appropriate labeling
1. Navigate to the dashboard
2. Look for the new "File Manager" section in the sidebar
3. Click on "Download Files"
4. Verify that both Account and Employee sections are visible
5. Confirm that file icons and XLS labels are properly displayed
To provide users with a dedicated interface for downloading account and employee-related files in XLS format, improving the accessibility and organization of exportable data within the application.

TIM-739 Add file manager download page and navigation

---

src/app/(dashboard)/(home)/(dashboard)/commission/commission-card.tsx
src/app/(dashboard)/(home)/(dashboard)/commission/commission-chart.tsx
src/app/(dashboard)/(home)/(dashboard)/commission/process-commission-chart.ts
src/app/(dashboard)/(home)/(dashboard)/page.tsx
supabase/seed.sql

Added a new commission chart component to display total commission earned over the last 12 months.
- Created a new commission card component with a chart visualization
- Added data processing logic to aggregate commission data by month
- Integrated the commission chart into the dashboard layout
- Updated seed data to include randomized creation dates for billing statements
1. Run the database seed script to populate test data
2. Navigate to the dashboard page
3. Verify the commission card displays with a chart showing last 12 months of data
4. Confirm the tooltip shows correct commission values when hovering over data points
5. Check that the chart properly aggregates commission data by month
This visualization helps users track their commission earnings trends over time, providing …

feat(dashboard): add commission earnings chart

---

src/app/(dashboard)/(home)/(dashboard)/commission/commission-card.tsx
src/app/(dashboard)/(home)/(dashboard)/commission/commission-chart.tsx
src/app/(dashboard)/(home)/(dashboard)/upcoming-renewals/renewal-card.tsx
src/app/(dashboard)/(home)/(dashboard)/upcoming-renewals/renewal-list.tsx

Improved responsive layout and scrolling behavior for dashboard cards
- Added fixed height (490px) to Commission and Renewal cards
- Updated column spans for better responsive behavior across different screen sizes
- Set explicit dimensions for Commission chart (400px height)
- Added scrollable behavior to Renewal list with max height of 370px
1. View dashboard at different screen sizes (mobile, tablet, desktop)
2. Verify Commission card spans correctly across breakpoints
3. Check that Commission chart renders properly with new dimensions
4. Add multiple renewal items and confirm scrolling works in Renewal card
To create a more consistent and polished dashboard layout that maintains proper spacing and alignment across all screen sizes while ensuring content remains accessible through …

feat(dashboard): adjust card heights and responsive layouts

---

src/app/(dashboard)/(home)/(dashboard)/page.tsx

Added role-based access control for dashboard components and implemented dynamic loading for renewal and commission cards.
- Implemented dynamic imports for RenewalCard and CommissionCard components
- Added loading states for dynamically imported components
- Integrated role-based access control using `getRole` utility
- Restricted RenewalCard and CommissionCard visibility to users with 'finance' or 'admin' roles
- Made Dashboard component asynchronous to support role checking
1. Log in as different user roles (admin, finance, and other roles)
2. Verify that RenewalCard and CommissionCard are only visible for admin and finance roles
3. Verify that loading states appear while cards are being dynamically loaded
4. Confirm that other dashboard components remain visible for all roles
To …

feat(dashboard): lazy load cards and add role-based visibility

---

src/app/(dashboard)/(home)/billing-statements/billing-statements-columns.tsx

Changed the commission earned column to display as currency instead of percentage.
Updated the formatting of the commission earned column in the billing statements table from `formatPercentage` to `formatCurrency`.
1. Navigate to the billing statements table
2. Verify that the "Commission Earned" column displays values in currency format (e.g., $100.00) rather than percentage format
Commission earned values should be displayed as monetary amounts rather than percentages to accurately represent the actual earnings in the billing statements.

fix(billing): change commission display from percentage to currency

---

src/app/(dashboard)/admin/agents/edit/edit-agent-form.tsx
src/app/(dashboard)/admin/users/edit/edit-user-form.tsx

Disabled email field editing for both users and agents in the admin forms.
- Made email fields permanently disabled in both user and agent edit forms
- Removed unused `ConfirmEmail` import from edit-user-form
- Replaced `disabled={isLoading}` with `disabled={true}` for email input fields
1. Navigate to the admin dashboard
2. Try to edit a user or agent
3. Verify that the email field is disabled and cannot be edited
4. Confirm that all other form fields remain editable
Email addresses serve as unique identifiers in the system and should not be modifiable after creation to maintain data integrity and prevent potential security issues. This change enforces this constraint at the UI level.

fix(forms): disable email field editing

---

src/app/(dashboard)/admin/approval-request/accounts/approval-request-info.tsx

Updated undefined fallback values to display a dash (-) in the approval request information panel
Replaced all instances of 'undefined' string fallbacks with a dash (-) character in the ApprovalRequestInfo component. This affects various fields including dates, commission rates, and currency values.
2. View an approval request with missing or undefined values
3. Verify that a dash (-) appears instead of the word 'undefined'
4. Check this behavior for:
- Date fields (expiration, effectivity, COC issue, etc.)
- Commission rate
- Total utilization
- Total premium paid
Displaying 'undefined' as text is not user-friendly and can be confusing for end users. Using a dash (-) is a more conventional and cleaner way to represent missing or undefined …

fix(admin): replace undefined with dash in approval info

---

src/app/(dashboard)/layout.tsx
src/app/(dashboard)/settings/account/page.tsx
src/components/layout/navigation/nav-user.tsx

Added user account settings navigation and placeholder page
- Created a new account settings page at `/settings/account`
- Enhanced the user navigation dropdown menu with links to account and security settings
- Added icons for better visual hierarchy in the navigation menu
- Reorganized the dropdown menu structure with proper grouping and separators
1. Log in to the application
2. Click on the user avatar in the navigation
3. Verify new "Account" and "Security" options are visible in the dropdown
4. Click "Account" to ensure it navigates to the new settings page
5. Verify the sign-out button is still accessible and functional
To provide users with easy access to account management features and establish a foundation for implementing account settings functionality. This improves the …

feat(settings): add account settings page and user menu links

---

src/app/(dashboard)/settings/(layout)/settings-nav-item.tsx
src/app/(dashboard)/settings/(layout)/settings-navigation.tsx
src/app/(dashboard)/settings/(layout)/settings-page-title.tsx
src/app/(dashboard)/settings/(layout)/settings-provider.tsx
src/app/(dashboard)/settings/account/page.tsx
src/app/(dashboard)/settings/layout.tsx

Added a responsive settings navigation layout with account and security sections.
- Created a new settings navigation component with a sidebar layout
- Implemented navigation items for Account and Security sections
- Added a settings context provider to manage sidebar state
- Built a responsive layout that adapts to mobile, tablet, and desktop views
- Created a page title component with a mobile menu toggle
1. Navigate to `/settings/account` or `/settings/security`
2. Verify the sidebar navigation appears and is functional
3. Test responsive behavior:
- On desktop: Sidebar should be permanently visible
- On mobile/tablet: Sidebar should slide in/out using the menu button
4. Confirm active state styling when navigating between sections
5. Verify smooth transitions and animations for the …

feat(settings): add responsive navigation layout

---

src/app/(dashboard)/settings/account/account-form.tsx
src/app/(dashboard)/settings/account/page.tsx
src/app/(dashboard)/settings/account/user-schema.ts
src/queries/get-current-user.tsx

Added account settings form to allow users to update their first and last name.
- Created a new account form component with first name and last name fields
- Added form validation using Zod schema
- Implemented user metadata update functionality using Supabase
- Added loading states and toast notifications for form feedback
- Created a new query helper for fetching current user data
1. Navigate to the account settings page
2. Try updating your first and last name
3. Verify that validation works when submitting empty fields
4. Confirm that success/error toasts appear after form submission
5. Refresh the page to verify that changes persist
Users need the ability to manage their basic profile information within the application. This change provides a simple interface for users to update …

feat(settings): add account form with name fields

---

src/app/(dashboard)/settings/security/page.tsx
src/app/(dashboard)/settings/security/security-form.tsx
src/app/(dashboard)/settings/security/security-schema.ts

Added a new security settings page allowing users to update their password with validation.
- Created a new security settings page with a password update form
- Added form validation using Zod schema to ensure passwords match and meet minimum requirements
- Implemented error handling and success notifications for password updates
- Enhanced the account form with improved error message display
1. Navigate to the security settings page
2. Attempt to update password with:
- Passwords less than 8 characters (should show validation error)
- Non-matching passwords (should show validation error)
- Valid matching passwords (should update successfully)
3. Verify error messages display correctly
4. Verify success toast appears after successful password update
To provide users with a secure and …

feat(settings): add security page with password update form

---

src/app/(dashboard)/(home)/file-manager/account-files/account-downloads.tsx
src/app/(dashboard)/(home)/file-manager/downloadable-files.tsx
src/app/(dashboard)/(home)/file-manager/downloads-provider.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads-button.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads-sheet.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads.tsx
src/app/(dashboard)/(home)/file-manager/page.tsx

Added employee downloads functionality and refactored downloads context provider for better reusability. HTML/CSS only.
- Created new employee downloads components including button, sheet, and downloads UI
- Renamed `AccountDownloadsProvider` to `DownloadsProvider` for broader usage
- Updated context usage across components to use the renamed provider
- Added sheet functionality to employee downloads with export and cancel actions
- Implemented file preview and information display in employee downloads sheet
1. Navigate to the file manager dashboard
2. Click on an employee file card to open the downloads sheet
3. Verify the file preview and information is displayed correctly
4. Confirm the Export File and Cancel buttons are present
5. Test sheet opening/closing functionality
6. Verify the …

TIM-741 Refactor downloads provider and add employee downloads sheet

---

package.json
pnpm-lock.yaml
src/app/(dashboard)/(home)/(dashboard)/page.tsx
src/app/(dashboard)/(home)/(dashboard)/retention-rate/retention-rate-card.tsx
src/app/(dashboard)/(home)/(dashboard)/top-hmo/count-hmo.ts
src/app/(dashboard)/(home)/(dashboard)/top-hmo/top-hmo-card.tsx
src/app/(dashboard)/(home)/(dashboard)/top-hmo/top-hmo-list.tsx
src/components/ui/progress.tsx

Added a new Top HMO Providers card to the dashboard that displays the top 3 HMO providers with visual progress indicators.
- Added a new Top HMO Providers dashboard card component
- Implemented progress bars with color-coded indicators based on percentage thresholds
- Created utility function to calculate HMO provider statistics
- Added @radix-ui/react-progress package for progress bar functionality
- Integrated the card into the main dashboard layout
1. Navigate to the dashboard
2. Locate the Top HMO Providers card
3. Verify that:
- The top 3 HMO providers are displayed
- Each provider shows account count and percentage
- Progress bars are color-coded (red < 5%, orange < 15%, yellow < 30%, green >= 30%)
- Rankings are correctly displayed
- Data updates when accounts are modified
To …

TIM-731 feat(home): add top hmo provider card

---

src/app/(dashboard)/(home)/(dashboard)/retention-rate/retention-rate-card.tsx
src/app/(dashboard)/(home)/(dashboard)/top-agents/top-agents-card.tsx
src/app/(dashboard)/(home)/(dashboard)/top-hmo/top-hmo-card.tsx
src/app/(dashboard)/(home)/(dashboard)/upcoming-renewals/renewal-card.tsx

Updated responsive grid layouts for dashboard cards to improve mobile and tablet display.
- Modified grid column spans for dashboard cards using Tailwind CSS classes
- Added breakpoints for medium (md), large (lg), and extra-large (xl) screen sizes
- Adjusted card layouts for Retention Rate, Top Agents, Top HMO, and Upcoming Renewals components
1. Open the dashboard on different screen sizes (mobile, tablet, desktop)
2. Verify cards stack properly on mobile devices
3. Confirm cards display in a 2-column layout on tablet/medium screens
4. Ensure cards expand to 4-columns on large screens
5. Check that cards revert to single column on extra-large screens where specified
To enhance the dashboard's responsiveness and improve user experience across different device sizes. The new layout …

feat(dashboard): update card grid responsiveness

---

src/app/(dashboard)/(home)/(dashboard)/commission/commission-chart.tsx
src/app/(dashboard)/(home)/(dashboard)/commission/process-commission-chart.ts
supabase/seed.sql

Updated commission chart to use `or_date` instead of `created_at` for date filtering and display.
- Modified commission chart query to select `or_date` instead of `created_at`
- Updated chart data processing to filter based on `or_date`
- Added null check for `or_date` in data processing
- Modified seed data to generate random `or_date` values within the last year
1. Run database migrations and seed data
2. Navigate to the commission chart view
3. Verify that commission data is displayed correctly based on OR dates
4. Confirm that the chart shows data for the last 12 months
The commission chart should reflect data based on when the Official Receipt (OR) was issued rather than when the record was created in the system, providing more accurate financial reporting.

fix(commission): use or_date instead of created_at for chart data

---

src/app/(dashboard)/(home)/file-manager/account-files/account-downloads-sheet.tsx
src/types/database.types.ts
supabase/migrations/20241117122414_add_approved_by_and_approved_at_columns_and_remove_default_value_on_created_by.sql

Added approval tracking fields to pending export requests and initialized Supabase client in downloads sheet.
- Added `approved_at` and `approved_by` columns to `pending_export_requests` table
- Created foreign key relationship between `approved_by` and `user_profiles.user_id`
- Set default value for `created_by` to `auth.uid()`
- Initialized Supabase browser client in AccountDownloadsSheet component
1. Create a new pending export request
2. Verify the `created_by` field is automatically populated
3. Approve a request and confirm both `approved_at` and `approved_by` fields are populated
4. Check that the foreign key relationship works by querying related user profile data
To track who approves export requests and when they were approved, providing better audit trails and accountability in …

TIM-747 Add approval tracking columns to pending export requests

---

package.json
pnpm-lock.yaml
src/app/(dashboard)/(home)/file-manager/downloads-page-title.tsx
src/app/(dashboard)/(home)/file-manager/export/employees-export.tsx
src/app/(dashboard)/(home)/file-manager/export/export-button.tsx
src/app/(dashboard)/(home)/file-manager/export/export-modal.tsx
src/components/ui/command.tsx

Added an export functionality to the file manager with a dropdown menu and modal interface for exporting employees and accounts.
- Added an Export button with a dropdown menu in the file manager header
- Created a new export modal component with support for employees and accounts
- Implemented an employee export interface with account selection using a searchable command menu
- Added the `cmdk` package for enhanced command menu functionality
- Created new UI components for the command interface
2. Click the Export button in the header
3. Select either "Employees" or "Accounts" from the dropdown
4. For employee exports:
- Search and select an account from the modal
- Verify the account selection updates correctly
- Test the cancel and export request buttons …

TIM-758 feat(export): add export modal on downloads page

---

src/app/(dashboard)/admin/approval-request/components/export-requests-approval-button.tsx

Added user tracking information when approving export requests.
When approving an export request, the system now captures the approver's ID and timestamp alongside the approval status.
1. Log in as an admin user
2. Navigate to the export requests approval page
3. Approve an export request
4. Verify in the database that the `approved_by` and `approved_at` fields are populated with the current user's ID and timestamp
To maintain an audit trail of who approved export requests and when they were approved, enhancing accountability and traceability in the system.

TIM-760 Change mutation when approving requests

---

src/app/(dashboard)/(home)/file-manager/account-files/account-downloads-sheet.tsx
src/queries/get-approved-exports.ts

Added approved_at date formatting and approver details to the downloads sheet
- Removed unused Supabase client import
- Added date formatting for the approved_at timestamp
- Displayed approver's first and last name in the downloads sheet
- Extended the database query to include approved_by and approved_at fields
- Removed TODO comment for button functionality
2. Open the downloads sheet for an approved file
3. Verify the approved_at date is properly formatted
4. Confirm the approver's full name is displayed correctly
To provide users with accurate information about when files were approved and who approved them, improving transparency and traceability in the file management system.

TIM-761 Add approval details to downloads sheet

---

src/app/(dashboard)/(home)/(dashboard)/commission/commission-chart.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-modal.tsx
src/app/(dashboard)/(home)/file-manager/export/employees-export.tsx

Removed console.log statements and implemented employee export functionality
- Removed debug console.log statements from commission chart and employee export modal
- Added export request functionality to the employees export component
- Implemented toast notifications for successful and failed export requests
- Added mutation handling for submitting export requests
2. Select an account from the dropdown
3. Click "Request Export"
4. Verify that a success toast appears
5. Verify that the export request is created in the pending_export_requests table
To clean up debugging code and implement the missing employee export functionality, providing users with the ability to request employee data exports while receiving appropriate feedback on the request status.

TIM-762 feat(export): add export employee function

---

src/app/(dashboard)/(home)/file-manager/export/accounts-export.tsx
src/app/(dashboard)/(home)/file-manager/export/export-modal.tsx

Added accounts export functionality to the file manager export modal
- Created a new `AccountsExport` component with export request functionality
- Updated `ExportModal` to handle accounts export type
- Added dynamic loading for the accounts export component
- Modified dialog description to be context-aware based on export type
2. Click on export accounts
3. Verify the export modal appears with the correct description
4. Click "Export Accounts" button
5. Confirm the success toast appears with the export request message
6. Verify the modal closes after submission
To provide users with the ability to export account data through a pending request system, ensuring proper approval workflow for sensitive account information exports

feat(export): add accounts export functionality

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-modal.tsx

Added employee data validation and mapping before export request creation
- Added validation to check if active employees exist before creating an export request
- Added error toast notification when no employee data is found
- Mapped employee data to exclude `id` and `account_id` fields from the export
- Included the processed employee data in the export request mutation
1. Navigate to the employee export modal
2. Try to create an export request with no active employees
3. Verify error toast appears
4. Add active employees and create an export request
5. Verify the export request contains the mapped employee data
To prevent creation of empty export requests and ensure only relevant employee data is included in the export. This improves data quality and user experience by providing …

TIM-772 Add employee data to export requests

---

src/app/(dashboard)/(home)/accounts/export-requests/export-accounts-modal.tsx
src/app/(dashboard)/(home)/accounts/export-requests/export-accounts.tsx
src/app/(dashboard)/(home)/file-manager/account-files/account-downloads-button.tsx
src/app/(dashboard)/(home)/file-manager/account-files/account-downloads-file-item.tsx
src/app/(dashboard)/(home)/file-manager/downloads-sheet.tsx

Enhanced the account export functionality to handle approved export requests and streamlined the export process.
- Modified the export accounts modal to use React Query for data fetching
- Removed unnecessary fields (id, created_at, updated_at) from exported data
- Updated the export accounts component to handle approved export requests
- Added export functionality to the downloads sheet
- Integrated export button with the file manager interface
1. Navigate to the accounts section
2. Create a new export request
3. Approve the export request
4. Go to the file manager
5. Select an approved account export
6. Click "Export File" to download the XLSX file
7. Verify the exported file contains the correct account data without system fields
To improve the security and control of the export …

feat(export): refactor accounts export functionality

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-modal.tsx

Removed additional system fields from employee export data
Updated the employee export modal to exclude internal system fields (`is_active`, `created_at`, `created_by`, `updated_at`) from the exported employee data, in addition to the previously excluded `id` and `account_id` fields.
1. Navigate to the employee export modal
2. Select employees to export
3. Generate an export
4. Verify that the exported data does not contain the following fields:
- id
- account_id
- is_active
- created_at
- created_by
- updated_at
To provide cleaner, more relevant data in employee exports by removing internal system fields that aren't meaningful to end users.

TIM-783 feat(export): remove additional fields from employee export data

---

src/app/(dashboard)/(home)/file-manager/page.tsx

Added server-side data prefetching for the File Manager page using React Query hydration.
- Converted the page component to a server component with 'use server'
- Implemented server-side data prefetching for approved exports using Supabase
- Added React Query hydration boundary to maintain data consistency
- Renamed the component from `Page` to `FileManagerPage` for better clarity
1. Navigate to the File Manager page
2. Verify that approved exports data loads immediately without loading states
3. Confirm that the data remains consistent during client-side navigation
4. Check that all file manager functionality continues to work as expected
This optimization improves the initial page load performance by prefetching necessary data on the server. It eliminates the need for client-side data …

feat(file-manager): add server-side data prefetching

---

src/app/(dashboard)/(home)/file-manager/account-files/account-downloads-file-item.tsx
src/app/(dashboard)/(home)/file-manager/account-files/account-downloads.tsx
src/app/(dashboard)/(home)/file-manager/downloads-page-title.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads-file-item.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads.tsx
src/app/(dashboard)/(home)/file-manager/export/export-button.tsx
src/app/(dashboard)/(home)/file-manager/page.tsx
src/queries/get-approved-exports.ts

Added support for displaying unapproved export files with visual indicators and tooltips.
- Added visual state for unapproved files (opacity reduced and cursor disabled)
- Implemented tooltips to indicate when files are not approved
- Modified query to fetch all export files instead of only approved ones
- Reordered export dropdown menu items (Accounts now appears before Employees)
2. Verify that unapproved files appear with reduced opacity
3. Hover over an unapproved file to see the "not approved" tooltip
4. Confirm that unapproved files cannot be clicked/selected
5. Check that the export dropdown shows "Accounts" before "Employees"
To improve user experience by showing all export files while clearly indicating their approval status, rather than hiding …

feat(export): add disabled state and tooltip for unapproved files

---

src/app/(dashboard)/(home)/file-manager/account-files/account-downloads.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads.tsx

Updated the file manager's grid layout to create a responsive, auto-filling grid for both account and employee downloads.
Replaced the flex row layout with a responsive grid layout in both `account-downloads.tsx` and `employee-downloads.tsx`. The new grid system automatically adjusts columns based on available space, with each column having a minimum width of 10rem.
1. Navigate to the file manager section
2. Check both account and employee download sections
3. Verify that files arrange in a grid pattern
4. Resize browser window to confirm responsive behavior
5. Ensure files remain centered and properly spaced
The previous flex row layout didn't efficiently use space or handle different screen sizes well. The new grid layout provides better organization of files, improved responsiveness, …

feat(downloads): improve file grid layout responsiveness

---

src/app/(dashboard)/(home)/file-manager/downloads-delete-button.tsx

Added file state reset when deleting downloads
Added `setFile(null)` when successfully deleting a download to ensure the file state is properly cleared
1. Navigate to the downloads section
2. Select a file to delete
3. Click delete and confirm the action
4. Verify that the sheet closes and no file remains selected
Previously, the file state wasn't being reset after deletion, which could lead to stale state and potential UI inconsistencies. This change ensures a clean state after file deletion.

TIM-786 Fix: Close sheet when file is deleted

---

src/app/(dashboard)/(home)/file-manager/account-files/account-downloads.tsx
src/app/(dashboard)/(home)/file-manager/downloads-sheet.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads.tsx
src/app/(dashboard)/(home)/file-manager/page.tsx

Implemented dynamic imports with loading states for file manager components to improve initial page load performance.
- Added dynamic imports for `AccountDownloadsFileItem`, `EmployeeDownloadsFileItem`, and `DownloadsSheet` components
- Implemented loading skeletons for file item components during lazy loading
- Disabled server-side rendering for export-related components
- Added loading states using the Skeleton component from the UI library
1. Navigate to the file manager page
2. Verify that file items load with skeleton placeholders initially
3. Confirm that all file management functionality works as expected after components load
4. Check that exports and downloads still function correctly
5. Verify that the sheet component opens and closes properly
By implementing dynamic imports and …

 TIM-721 feat(perf): implement dynamic imports for file manager components

---

src/app/(dashboard)/(home)/file-manager/page.tsx
src/app/(dashboard)/admin/approval-request/account-exports/page.tsx
src/app/(dashboard)/admin/approval-request/employee-exports/page.tsx

Added page titles to File Manager and Export Request pages
- Added metadata export with page titles for:
- File Manager page
- Account Export Requests page
- Employee Export Requests page
- Reorganized imports for better code organization
1. Navigate to the File Manager page and verify the browser tab shows "File Manager"
2. Visit the Account Export Requests page and confirm the title shows "Account Export Requests"
3. Check the Employee Export Requests page and ensure the title displays "Employee Export Requests"
Improves user experience by providing clear page identification in browser tabs, making it easier for users to navigate between multiple open tabs and understand their current location in the application.

feat(pages): add metadata titles to file manager pages

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/fields.ts

Added member type, dependent relation, and expiration date fields to employee import functionality and updated example values.
- Added three new import fields:
- Member Type (select field with Principal/Dependent options)
- Dependent Relation (select field with Spouse/Child/Parent options)
- Expiration Date (input field)
- Updated example values for name fields to use "Francisco, Monds" instead of previous examples
1. Navigate to the employee import feature
2. Upload a CSV file containing member type, dependent relation, and expiration date columns
3. Verify that the new fields are properly mapped during the import process
4. Confirm that both principal and dependent relationships can be imported
5. Validate that expiration dates are correctly processed
To support the import of dependent …

feat(import): add member type and expiration fields

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-actions-dropdown.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-information/employee-form.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-schema.ts
src/components/ui/select.tsx

Added new fields to the employee form including member type, dependent relation, expiration date, cancelation date, and remarks.
- Implemented dynamic imports for employee-related components to improve initial load performance
- Added new form fields:
- Member Type (principal/dependent dropdown)
- Dependent Relation (spouse/child/parent dropdown)
- Expiration Date (calendar picker)
- Cancelation Effective Date (calendar picker)
- Remarks (text input)
- Updated employee schema to include new field validations
- Modified select component cursor style from default to pointer
1. Navigate to the employee form
2. Verify all new fields are present and functional:
- Select different member types
- Choose dependent relations
- Set expiration and cancelation dates
- Add remarks
3. Submit the form …

feat(employees): add member type and dependent fields

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-about.tsx
src/app/(dashboard)/(home)/accounts/add-account-form.tsx
src/app/(dashboard)/(home)/accounts/data-table.tsx
src/app/(dashboard)/layout.tsx
src/providers/UserProvider.tsx
supabase/migrations/20241128122627_refactor_rls_on_accounts_table.sql

Implemented department-based permissions for account management, allowing marketing users to submit changes for approval while other departments can modify accounts directly.
- Added UserProvider context to manage user state across the application
- Modified account creation and editing logic to handle different department permissions
- Marketing department users now submit changes to `pending_accounts` table
- Other authorized departments can directly modify the `accounts` table
- Updated RLS policies to restrict account modifications to specific departments
- Added conditional rendering of account request features for marketing users
- Improved error handling for duplicate company names
1. Log in as a marketing department user
- Verify that account changes create pending requests
- …

TIM-800 refactor(accounts): department request permissions

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-HMO-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-account-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-contract-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-header.tsx

Improved responsive layout for company profile sections and header components
- Converted grid layouts to flex column on mobile for better content stacking
- Added responsive breakpoints for grid layouts on medium and larger screens
- Enhanced company name text wrapping and overflow handling
- Adjusted company header dimensions and spacing
- Updated avatar positioning and container width
1. Navigate to a company profile page
2. Verify layout responsiveness by testing on different screen sizes:
- Mobile: Content should stack vertically
- Tablet (md): Should display 2-column grid
- Desktop (lg/xl): Should maintain proper spacing and grid layouts
3. Test with long company names to ensure proper text wrapping
4. Confirm avatar and header positioning across all breakpoints
To enhance the …

TIM-789 feat(ui): improve company profile responsive layout

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-about.tsx
src/app/(dashboard)/(home)/accounts/add-account-form.tsx
src/app/(dashboard)/(home)/accounts/data-table.tsx
src/app/(dashboard)/admin/approval-request/accounts/action-request-button.tsx

Added after-sales department to pending accounts workflow and implemented duplicate company name validation.
- Extended pending accounts functionality to include after-sales department alongside marketing
- Added validation to prevent duplicate company names during account approval
- Updated success messages and notifications to reflect the new department inclusion
- Modified database insertion logic to handle both marketing and after-sales departments
1. Log in as an after-sales user and attempt to create/edit an account
2. Verify the request goes to pending_accounts
3. Try approving an account with a company name that already exists
4. Confirm appropriate success/error messages are displayed
5. Test the same workflow as a marketing user to ensure existing functionality remains
To …

feat(accounts): add after-sales to pending accounts flow

---

supabase/migrations/20241205055926_refactor_rls_for_accounts.sql

Updated RLS policies for accounts table to restrict access to specific departments
- Dropped and recreated insert and update policies for the accounts table
- Refined policy conditions to only allow access for users in admin, finance, or under-writing departments
- Policies now verify department access through user_profiles and departments tables
1. Log in as a user from admin, finance, or under-writing department
- Verify you can insert and update accounts
2. Log in as a user from any other department
- Verify you cannot insert or update accounts
3. Verify existing records remain accessible according to policy
To enforce stricter access control by ensuring only users from authorized departments can modify account data, improving security and data integrity

refactor(accounts): update department RLS policies
