TimBuilding/wisecare

package.json
pnpm-lock.yaml
src/app/(dashboard)/layout.tsx
src/app/globals.css
src/components/layout/header.tsx
src/components/layout/navbar.tsx
src/components/layout/navigation.tsx
src/components/ui/sheet.tsx
tailwind.config.js

Updated dependencies and added a new Navbar component for layout. Implemented sheet UI for mobile view.
- Updated dependencies
- Added Navbar component for layout
- Implemented sheet UI for mobile view
- Verify that dependencies are updated successfully
- Test the Navbar component in the layout
- Test the sheet UI for mobile view
The changes were implemented to enhance the layout and user experience of the application.
---

TIM-184 feat(layout): add navigation

---

src/app/(auth)/forgot-password/forgot-password-form.tsx
src/app/(auth)/forgot-password/forgot-password-schema.ts
src/app/(auth)/forgot-password/page.tsx
src/app/(auth)/sign-in/sign-in-form.tsx

Added a forgot password feature to the authentication flow.
- Created a new `ForgotPasswordForm` component with form validation and error handling
- Implemented a `ForgotPasswordSchema` for input validation
- Added a new `ForgotPasswordPage` component
- Updated the `SignInForm` to include a link to the forgot password page
1. Navigate to the sign-in page
2. Click on the "Forgot password?" link
3. Enter a valid email address in the forgot password form
4. Submit the form and verify that a success toast message appears
5. Check that an email with password reset instructions is received
This change enhances user experience by providing a way for users to reset their passwords if forgotten. It's a standard feature in authentication systems and improves overall account security and …

TIM-162 feat(auth): add reset-password feature

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-HMO-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-about.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-account-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-cancel-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-contract-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-edit-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-edit-provider.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-financial-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-page.tsx

Submit button isn't working pa. Will fix tomorrow.

TIM-387 Add forms and context to edit company details

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-HMO-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-about.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-account-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-contract-information.tsx

TIM-355 Fix company profile won't open

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-header.tsx

[![acceptit](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WjlTemxb6oA4PgZFmj08/8488a0d6-7bb9-488a-90cd-060d546900aa/acceptit.gif)](https://app.graphite.dev//settings/meme-library?org=TimBuilding)

TIM-398 Fix Company Profile Header formatting

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-HMO-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-about.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-account-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-contract-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-edits-schema.ts
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-financial-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-information.tsx

Enhanced form handling and data management for company information editing
- Implemented form context and schema validation using `react-hook-form` and `zod`
- Added `companyEditsSchema` to define the structure and validation rules for company edits
- Updated form fields to use `FormField`, `FormControl`, and `FormItem` components
- Integrated form state management across various company information components
- Added new fields for comprehensive company data capture
- Improved error handling and form submission process
1. Navigate to a company's edit page
2. Enable edit mode and modify various fields across different sections
3. Verify that form validation works correctly for all fields
4. Submit the form and check if the data is correctly updated in the database
5. Test error scenarios …

TIM-400 Fix submit button on edit company details

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-delete-button.tsx
src/app/globals.css
src/components/ui/button.tsx
tailwind.config.js

Improved button styling and consistency across the application.
- Updated the `CompanyDeleteButton` component to use the `destructive` variant instead of custom styling.
- Added a new `destructive-hover` color variable in `globals.css`.
- Modified the `buttonVariants` in the `button.tsx` component to use the new `destructive-hover` color and updated the `outline` variant hover state.
- Added the `destructive-hover` color to the Tailwind configuration.
1. Navigate to the company delete button in the Personnel accounts section.
2. Verify that the button styling is consistent with other destructive buttons.
3. Hover over the button to ensure the hover state is working correctly.
4. Test other button variants across the application to ensure they maintain their expected appearance and …

TIM403 fix(ui): update button styles and destructive color handling

---

src/types/database.types.ts
supabase/migrations/20241015102724_add_billing_statements_table.sql
supabase/seed.sql

Added a new `billing_statements` table with associated types and RLS policies.
- Created a new `billing_statements` table in the database
- Added corresponding types for the `billing_statements` table in `database.types.ts`
- Implemented Row Level Security (RLS) policies for the `billing_statements` table
- Restricted access to finance department users for select, insert, and update operations
1. Run the migration to create the `billing_statements` table
2. Verify the table structure in the database
3. Test RLS policies:
- Log in as a finance department user and attempt to select, insert, and update records
- Log in as a non-finance user and verify that access is restricted
4. Check that the new types are correctly reflected in the application code
This change introduces a new table to …

TIM-426 feat(billing): add billing_statements table and types

---

supabase/migrations/20241016052830_alter_accounts_policy.sql

[![deletethepast](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WjlTemxb6oA4PgZFmj08/b2faa6c4-10e2-4279-aa40-59ca294260f5/deletethepast.gif)](https://app.graphite.dev//settings/meme-library?org=TimBuilding)

TIM-419 Underwriting and after sales should be able to add, edit and delete accounts

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-page.tsx

[![kanyewow](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WjlTemxb6oA4PgZFmj08/4c4a23b5-781b-4244-99db-a780a01f1d64/kanyewow.gif)](https://app.graphite.dev//settings/meme-library?org=TimBuilding)

TIM-441 Add roles for delete button on company profile

---

src/app/(dashboard)/(home)/billing-statements/data-table.tsx
src/types/database.types.ts
supabase/migrations/20241016065116_fix_search_billing_statements_rpc.sql

Improved billing statements search functionality and updated related components.
- Replaced inline search component with `TableSearch` in `data-table.tsx`
- Added `account_id` field to `billing_statements` table in database types
- Created a new migration file to update the `search_billing_statements` function
- Updated `search_billing_statements` function to include account information and improve search capabilities
1. Run the new migration to update the `search_billing_statements` function
2. Navigate to the billing statements page
3. Use the search functionality to search for billing statements by account name
4. Verify that the search results include account information and are filtered correctly
This change enhances the billing statements search functionality by:
1. Improving code …

TIM-430 feat(billing-statements): add search functionality

---

package.json
pnpm-lock.yaml
src/app/(dashboard)/(home)/billing-statements/add-billing-statement-button.tsx
src/app/(dashboard)/(home)/billing-statements/billing-statement-schema.ts
src/app/(dashboard)/(home)/billing-statements/billing-statements-columns.tsx
src/app/(dashboard)/(home)/billing-statements/data-table.tsx
src/components/billing-statement/billing-statement-form.tsx
src/queries/get-all-accounts.ts
src/types/database.types.ts
supabase/migrations/20241016084944_delete_mode_of_premium_on_billing_statements.sql
supabase/migrations/20241016090139_fix_search_billing_statement_rpc.sql
supabase/seed.sql

Added functionality to create and display billing statements, including a new modal for adding statements and updated database schema.
- Created a new `AddBillingStatementModal` component for adding billing statements
- Added `BillingStatementSchema` for form validation
- Updated `billing-statements-columns.tsx` to display billing statement data
- Modified `data-table.tsx` to include the new Add Billing Statement button
- Updated database schema: renamed `mode_of_premium_id` to `mode_of_payment_id` in billing_statements table
- Added new migration files for database changes
- Updated seed data to reflect schema changes
- Modified `search_billing_statements` function to work with updated schema
1. Navigate to the billing statements page
2. Click on "Add Billing Statement" button
3. Fill …

TIM-445 feat(billing-statements): create add-billing-statement feature

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/delete-employee.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-details.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-form-modal.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-columns.tsx

Enhanced employee management functionality with new details view and role-based access control.
- Added a new `EmployeeDetails` component to display comprehensive employee information in a modal dialog.
- Implemented role-based access control for the delete employee functionality.
- Updated the employee table columns to include a "View Details" option in the dropdown menu.
- Removed unnecessary imports and components from various files.
- Adjusted the layout of the employee form modal for better readability.
1. Navigate to the employee management page.
2. Click on the dropdown menu for an employee and verify that the "View Details" option is present.
3. Click "View Details" and ensure that the modal displays all employee information correctly.
4. Test the delete employee functionality …

feat(employees): add employee details view and enhance delete functionality

---

package.json
pnpm-lock.yaml
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-data-table.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-table-search.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/company-page.tsx

Implemented global search functionality for the employees data table and refactored related components.
- Added a new `EmployeesTableSearch` component for global search functionality.
- Updated `EmployeesDataTable` to use the new global search component and handle global filtering.
- Removed the column-specific search for the 'first_name' column.
- Added 'match-sorter-utils' as a dev dependency in `package.json` and `pnpm-lock.yaml`.
- Removed unused `showAddPersonnel` from the `CompanyPage` component.
1. Navigate to the employees data table.
2. Use the new search input to filter employees across all columns.
3. Verify that the search works correctly for various employee attributes.
4. Ensure that the table updates in real-time as you type in the search input.
This change improves the …

TIM-463 feat(employees): improve search function to filter all columns

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-columns.tsx

Updated the formatting of the effective date in the employees table.
Modified the `cell` function for the 'Effective Date' column in the employees table. The function now checks if an effective date exists before attempting to format it. If there's no date, it returns an empty string instead of potentially causing an error.
1. Navigate to the employees table in the dashboard.
2. Verify that employees with an effective date show the date formatted correctly.
3. Confirm that employees without an effective date display an empty cell instead of an error or invalid date.
This change improves the robustness of the date display in the employees table. It prevents potential errors when dealing with null or undefined effective dates, ensuring a smoother user experience and more reliable data …

TIM-471 fix(employees): null values to be blank

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-delete-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-tab.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-employees.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-add-personnel-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/employees-add-personnel-form.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/layout.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/page.tsx

Improved company account page handling and navigation.
- Added router navigation after deleting a company account
- Implemented server-side rendering for the company account page
- Moved hydration boundary and company provider to the layout component
- Added a check for active accounts and implemented a not found redirect
- Simplified the page component by removing unnecessary code
1. Navigate to a company account page
2. Attempt to delete the company account
3. Verify that you are redirected to the accounts page after deletion
4. Try accessing an inactive or non-existent company account
5. Confirm that you are redirected to a not found page
These changes improve the user experience by providing better navigation after account deletion and handling inactive or non-existent accounts. The …

feat(accounts): enhance company deletion and improve page routing

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(billing statements)/billing-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(billing statements)/billing-statements.tsx

Enhanced null handling in billing information display and improved date formatting
- Added proper null checks for all billing information fields using ternary operators
- Improved date formatting logic for due dates and OR dates
- Standardized the display of default values when data is missing
- Reorganized imports for better code organization
1. Navigate to the billing information section
2. Verify that fields display 'N/A' when data is null/undefined
3. Check that dates are properly formatted when present
4. Confirm that numerical values default to '0' or 'N/A' when missing
To prevent potential rendering errors and provide a more consistent user experience when dealing with missing or null data in the billing information display. This change makes the interface more robust and …

fix(billing): handle null values in billing information display

---

package.json
pnpm-lock.yaml
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-contract-information.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-form.tsx
src/app/(dashboard)/(home)/accounts/accounts-schema.ts
src/app/(dashboard)/(home)/accounts/forms/marketing-inputs.tsx
src/components/billing-statement/billing-statement-modal.tsx
src/components/maskito/options.ts

Enhanced date picker functionality and added input masking for dates.
- Added @maskito packages for input masking
- Updated date picker components with improved functionality:
- Added dropdown layout for month and year selection
- Set year range from 1900 to 20 years in the future
- Customized styling for better visibility and interaction
- Modified date validation to allow future dates where appropriate
- Updated company name validation to require at least one character
- Adjusted grid layout for better responsiveness in company contract information
1. Navigate to forms with date inputs (e.g., company contract information, employee forms, marketing inputs)
2. Verify that date pickers now have dropdown selectors for month and year
3. Check that year range is from 1900 to 20 years in the …

TIM-487 feat(forms): improve calendar by adding year and month selector

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-account-information.tsx
src/app/(dashboard)/(home)/accounts/forms/marketing-inputs.tsx
src/app/(dashboard)/admin/agents/agents-count.tsx
src/app/(dashboard)/admin/agents/agents-list.tsx
src/queries/get-agents.ts

Updated agent data retrieval and display across multiple components.
- Modified `getAgents` query to directly fetch user profiles with department information.
- Updated components to handle the new data structure:
- `CompanyAccountInformation` and `MarketingInputs` now map directly over `agents` instead of `agents[0].user_profiles`.
- `AgentsCount` now uses the `count` property from the query result.
- `AgentsList` maps directly over `data` instead of `data[0].user_profiles`.
1. Navigate to the company account information page and verify that agent selection works correctly.
2. Check the marketing inputs form to ensure agent selection is functioning properly.
3. Visit the admin agents page and confirm that the agent count and list are displayed accurately.
This change simplifies the data …

refactor(agents): optimize agent data fetching and rendering

---

src/app/(dashboard)/(home)/accounts/add-account-button.test.tsx
src/test/test-utils.tsx

Added unit tests for the AddAccountButton component and created a custom test utility file.
- Created a new test file `add-account-button.test.tsx` for the AddAccountButton component.
- Implemented tests to verify the button's visibility based on different user roles.
- Added a test to check if the modal opens when the button is clicked.
- Created a new `test-utils.tsx` file with custom render function and necessary providers for testing.
1. Run the test suite using the command `npm test` or `yarn test`.
2. Verify that all tests pass successfully.
3. Check the test coverage for the AddAccountButton component.
This change improves the test coverage of the AddAccountButton component, ensuring that it behaves correctly for different user roles. The new test utility file provides a consistent …

feat(accounts): add tests for AddAccountButton and test utils

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-columns.tsx

Updated date formatting and handling in employee columns
- Modified the `birth_date` and `effective_date` columns to use `accessorFn` instead of `cell` for date formatting
- Implemented null checks for date values to prevent errors with undefined dates
- Simplified the date formatting logic for both columns
1. Navigate to the employee list view
2. Verify that birth dates and effective dates are correctly displayed
3. Check that empty or null date fields are handled gracefully (displayed as empty strings)
4. Ensure that valid dates are formatted consistently using the 'PP' format
This change improves the robustness of date handling in the employee columns. By using `accessorFn`, we can preprocess the date values before they're used in the table, which can lead to better performance. The …

feat(employees): refactor date formatting for birth and effective dates

---

src/app/(dashboard)/admin/approval-request/billing-statements/billing-statement-action-button.tsx

Implemented proper context handling and success notifications for billing statement approvals/rejections.
- Added proper context import for billing statements
- Implemented success toast notifications for approve/reject actions
- Added type safety checks for selected data
- Fixed account and mode of payment ID references
- Removed unused context implementation stub
1. Navigate to the billing statements approval section
2. Select a billing statement
3. Click approve or reject
4. Verify that a success notification appears
5. Confirm the modal closes automatically
6. Verify the statement status updates correctly
To improve user feedback during the approval/rejection process and ensure proper data handling through the context system. This change also removes redundant code and adds necessary …

TIM-587 feat(billing-statements): add approval function for billing statements

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(company profile)/company-about.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/delete-employee.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-form.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-columns.tsx
src/app/(dashboard)/(home)/accounts/add-account-form.tsx
src/app/(dashboard)/admin/approval-request/company-employees/employee-action-button.tsx
src/queries/get-pending-company-employees.ts
src/types/database.types.ts
supabase/migrations/20241104025632_add_rls_for_updating_company_employees.sql

Added approval workflow for employee management operations and improved notification messages.
- Modified employee deletion to create pending requests instead of direct deletion
- Updated success messages to reflect pending approval status
- Added new database column `company_employee_id` to track original employee records
- Implemented RLS policies for admin-specific operations
- Enhanced foreign key relationships between employees and user profiles tables
- Updated employee action handling in the admin approval interface
1. Try to add a new employee and verify the pending approval message
2. Attempt to delete an employee and confirm it creates a pending request
3. Log in as admin and verify approval requests are visible
4. Test employee approval/rejection workflow
5. Verify foreign key …

feat(employees): implement employee approval request workflow

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-data-table.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/fields.ts
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/import-employees-button.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/import-employees.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/parseDate.ts
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/import/parseRow.ts

Enhanced the employee import functionality with improved date parsing and name handling capabilities.
- Created a new `ImportEmployeesButton` component to handle the import modal state
- Added additional name matching patterns for better column recognition
- Implemented dedicated `parseDate` utility to handle various date formats
- Improved name parsing logic to handle comma-separated full names
- Made the import component client-side only with `ssr: false`
1. Navigate to the employees section
2. Click the "Import" button
3. Try importing files with different date formats (MM/DD/YYYY or DD MMM YYYY)
4. Test importing files with names in different formats, especially comma-separated ones
5. Verify that the imported data is correctly parsed and formatted
To improve the robustness of the …

feat(employees): improve import functionality with date parsing

---

src/app/(dashboard)/admin/approval-request/accounts/page.tsx
src/app/(dashboard)/admin/approval-request/billing-statements/loading.tsx
src/app/(dashboard)/admin/approval-request/billing-statements/page.tsx

Added loading state and dynamic imports for billing statement approval page
- Created a new loading component for billing statements approval page
- Implemented dynamic import for BillingStatementInfo component
- Wrapped BillingStatementInfo in a Suspense boundary with fallback
- Disabled server-side rendering for BillingStatementInfo
1. Navigate to the billing statements approval page
2. Verify loading skeleton appears while page is loading
3. Confirm BillingStatementInfo loads correctly after initial page load
4. Check that the loading fallback appears briefly during component load
Improves initial page load performance by deferring the loading of the BillingStatementInfo component and provides a better user experience with loading states while content is being fetched.

feat(billing): optimize statement info with dynamic loading

---

src/app/(dashboard)/admin/approval-request/company-employees/loading.tsx
src/app/(dashboard)/admin/approval-request/company-employees/page.tsx

Added loading state and dynamic imports for the company employees approval page.
- Created a new loading component for the company employees approval page
- Implemented dynamic import for `PendingEmployeeInfo` component
- Wrapped `PendingEmployeeInfo` with Suspense boundary
- Added loading skeleton UI with page header and title
1. Navigate to the company employees approval page
2. Verify loading skeleton appears while content is loading
3. Confirm dynamic loading of employee information works correctly
4. Check that the page transitions smoothly between loading and loaded states
Improves initial page load performance by implementing lazy loading and providing visual feedback during loading states. This enhances user experience by showing loading indicators and reducing the initial bundle …

feat(employees): optimize approval page with dynamic loading

---

src/app/(dashboard)/admin/users/create/add-user-form.tsx
src/app/(dashboard)/admin/users/create/add-user.tsx
src/app/(dashboard)/admin/users/loading.tsx
src/app/(dashboard)/admin/users/user-list.tsx

Added dynamic loading and loading states for user management components
- Implemented dynamic imports for AddUserForm and EditUserForm components
- Added a loading state component for the users page
- Wrapped form components with Suspense boundaries and fallback states
- Removed unused SheetFooter import
1. Navigate to the admin users page
2. Verify loading states appear when adding/editing users
3. Confirm forms load correctly after the loading state
4. Check that user management functionality continues to work as expected
This change improves the initial page load performance by lazy loading form components and providing better loading states. The dynamic imports ensure that form-related code is only loaded when needed, reducing the initial bundle size and improving the user experience.

feat(users): optimize form loading with dynamic imports and suspense

---

src/app/(dashboard)/admin/agents/agents-list.tsx
src/app/(dashboard)/admin/agents/create/add-agent.tsx
src/app/(dashboard)/admin/agents/loading.tsx
src/app/(dashboard)/admin/users/create/add-user.tsx

Added dynamic imports and loading states for agent and user management components
- Implemented dynamic imports for `EditAgentForm`, `AddAgentForm`, and Avatar components
- Added Suspense boundaries with skeleton loading states for avatars
- Created a new loading state component for the Agents page
- Standardized the loading experience across user and agent management interfaces
1. Navigate to the admin/agents and admin/users pages
2. Open the add/edit forms for both agents and users
3. Verify skeleton loaders appear while components are loading
4. Confirm avatars and forms load correctly after the initial loading state
This optimization improves the initial page load performance by lazy loading heavy components and providing a smooth loading experience with skeleton states. This prevents …

feat(agents): optimize avatar loading with dynamic imports

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employees-columns.tsx

Simplified the employee table by removing unnecessary columns and prioritizing essential information.
- Reordered columns to show card number first, followed by name and gender
- Removed columns for birth date, civil status, and effective date
- Maintained the actions column for user interactions
1. Navigate to the Personnel section
2. Open any company's employee list
3. Verify that the table displays only card number, first name, last name, gender, and actions
4. Confirm that the data in each column is correctly formatted and displayed
To improve table readability by focusing on the most frequently used information and removing less essential details that can be accessed through other interfaces when needed.

refactor(employees): simplify table columns

---

src/app/(dashboard)/(home)/(dashboard)/client-acquisition/client-acquisition-chart.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/employee-information/employee-form.tsx
src/app/(dashboard)/admin/approval-request/billing-statements/billing-statement-action-button.tsx

Fixed missing dependencies in useEffect and useCallback hooks across multiple components.
- Added `rerender` to dependency array in ClientAcquisitionChart's useEffect
- Updated dependency array in EmployeeForm to include full `oldEmployeeData` object instead of just `oldEmployeeData.id`
- Added `setIsLoading` to dependency array in BillingStatementActionButton's useEffect
1. Verify ClientAcquisitionChart updates correctly when data changes
2. Test employee form editing functionality
3. Check billing statement action button loading states work as expected
React's exhaustive-deps ESLint rule identified missing dependencies that could lead to stale closures and unexpected behavior. These changes ensure the hooks properly react to all their dependencies, preventing potential bugs and …

fix(deps): add missing useEffect dependencies

---

src/app/(dashboard)/admin/approval-request/account-exports/account-export-requests-table.tsx

Added search functionality to the Account Export Requests table
- Imported and implemented the TableSearch component in the account export requests table
- Removed TODO comment placeholder
- Enabled search functionality for account export requests
2. Locate the account export requests table
3. Use the search field to filter through requests
4. Verify that search results update as you type
To improve user experience by allowing administrators to quickly find specific account export requests through search functionality, rather than manually scanning through the entire table.

TIM-689 Add table search component on account exports table

---

src/app/(dashboard)/admin/approval-request/employee-exports/employee-exports-requests-table.tsx

Added search functionality to the employee exports requests table
- Imported the TableSearch component
- Implemented the search component in the employee exports requests table, replacing the TODO comment
1. Navigate to the admin approval request page for employee exports
2. Verify that the search input field is visible in the table header
3. Enter search terms and confirm that the table filters results accordingly
To enable users to quickly find specific employee export requests by searching through the table data, improving the overall user experience and efficiency of managing export requests.

TIM-697 Add search component on employee exports table

---

src/app/(dashboard)/admin/agents/create/add-agent-form.tsx
src/app/(dashboard)/admin/agents/edit/edit-agent-form.tsx
src/app/(dashboard)/admin/users/create/add-user-form.tsx
src/app/(dashboard)/admin/users/edit/edit-user-form.tsx
src/app/api/users/route.ts

Fixed error handling in user and agent forms and improved form state management after submissions.
- Added proper loading state reset when errors occur in forms
- Added automatic form closure after successful submissions
- Updated API error responses to return specific error messages instead of generic failures
- Added early returns after error states to prevent further execution
1. Try creating/editing a user or agent with invalid data
2. Verify that loading states properly reset on error
3. Verify that forms automatically close after successful submissions
4. Confirm that error messages are specific and helpful
5. Ensure the form loading indicator behaves correctly in all scenarios
Forms were not properly handling error states, leading to stuck loading indicators and unclear error …

fix(forms): handle loading states and error handling

---

src/app/(dashboard)/(home)/file-manager/account-files/account-downloads-sheet.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads-file-item.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads-sheet.tsx
src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads.tsx
src/queries/get-approved-employee-exports.ts

Added file download functionality for employee exports with improved UI components
- Created new `EmployeeDownloadsFileItem` component for displaying individual employee export files
- Implemented file selection and preview functionality in employee downloads sheet
- Added query to fetch approved employee exports from the database
- Fixed file extension badge positioning in download items
- Restructured employee downloads view to display multiple export files
1. Navigate to the file manager section
2. Check if employee export files are displayed with proper XLS badges
3. Click on any employee export file to open the preview sheet
4. Verify that company name and creation date are displayed correctly
5. Test the download functionality using the download button
To provide users with a …

TIM-747 Fix file item positioning and add employee downloads component

---

src/app/(dashboard)/(home)/file-manager/employee-files/employee-downloads-sheet.tsx
src/app/(dashboard)/(home)/file-manager/page.tsx

Added company name and dynamic approval information to the employee downloads sheet.
- Added company name display to the employee downloads sheet
- Integrated dynamic approval date using `formatDate` from date-fns
- Added dynamic approved by information showing first and last name
- Included EmployeeDownloadsSheet component in the file manager page
- Removed TODO comment for buttons functionality
1. Navigate to the file manager page
2. Open the employee downloads sheet
3. Verify company name is displayed correctly
4. Confirm approval date is formatted properly
5. Check that approver's full name is shown correctly
To provide users with more detailed and accurate information about file downloads, including company context and approval details. This improves transparency and helps users …

TIM-747 Add company name and approval details to employee downloads sheet

---

src/app/globals.css
src/app/layout.tsx

Updated color scheme variables and theme configuration for improved visual consistency
- Adjusted color variables for destructive states and chart colors
- Modified sidebar color palette for better contrast
- Changed default theme from dark to light
- Disabled system theme preference
- Added hydration warning suppression to HTML element
1. Launch the application
2. Verify the new color scheme in both light and dark modes
3. Check that charts display with updated colors
4. Confirm sidebar styling matches new design
5. Verify theme defaults to light mode
6. Ensure no hydration warnings appear in console
To enhance visual hierarchy and improve color accessibility while providing a more consistent user experience across the application. The new color palette offers better contrast ratios and …

feat(theme): update color scheme and default theme settings

---

src/app/(dashboard)/(home)/accounts/export-requests/export-accounts-modal.tsx
src/app/(dashboard)/(home)/accounts/export-requests/export-accounts.tsx

Enhanced account export functionality with improved data formatting and column sizing
- Restructured account export data fields with proper column headers and formatting
- Added column width standardization (30 characters) for better spreadsheet readability
- Included additional account fields in the export such as Company Name, Contact Details, and Benefit Information
- Removed unnecessary console logging
- Excluded inactive account status from export data
1. Navigate to the accounts export section
2. Generate a new export request
3. Download and open the exported Excel file
4. Verify that:
- All columns are properly sized and readable
- Column headers are properly formatted
- All account information is present and correctly displayed
- No inactive account status field is included
To …

TIM-781 feat(export): enhance accounts export formatting and fields

---

src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-employees.tsx
src/app/(dashboard)/(home)/accounts/(Personnel)/[id]/(employees)/export-requests/employee-export-modal.tsx
src/app/(dashboard)/(home)/accounts/export-requests/export-accounts-modal.tsx

Enhanced Excel export functionality with improved column formatting and standardized data structure
- Added automatic column width adjustment (30 characters) for exported Excel files
- Standardized employee data export format with specific column headers
- Restructured employee data mapping to include clear, human-readable column names
- Cleaned up import statements and removed unused components
1. Navigate to the employee export feature
2. Export employee data to Excel
3. Verify that:
- Column widths are consistent (30 characters)
- Column headers are human-readable (e.g., 'First Name', 'Last Name')
- All employee data fields are properly formatted
- Excel file opens without any formatting issues
To improve the readability and usability of exported Excel files by implementing consistent …

TIM-782 feat(export): enhance employee export formatting and column width
